"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import Image from "next/image";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ProjectImage, ProjectReference, ProjectVideo, SectorProject } from "@/lib/sector-projects";
import { assetPath } from "@/lib/site";

type Filters = { sector: string; environment: string; product: string; city: string; application: string };
const emptyFilters: Filters = { sector: "", environment: "", product: "", city: "", application: "" };
const unique = (values: readonly string[]) => [...new Set(values)].sort((a, b) => a.localeCompare(b, "tr"));

function VideoPanel({ video }: { video: ProjectVideo }) {
  const [active, setActive] = useState(false);
  const permitted = video.publicationPermission === "granted" && Boolean(video.url);
  return <section className="project-video" aria-labelledby="project-video-title"><h3 id="project-video-title">{video.title}</h3><div className="project-video-frame">{active && permitted ? video.type === "local" ? <video controls preload="metadata" poster={assetPath(video.posterImage)}><source src={assetPath(video.url)} /></video> : <iframe src={video.url} title={video.title} loading="lazy" allow="fullscreen; picture-in-picture" allowFullScreen /> : <><Image src={assetPath(video.posterImage)} alt={video.posterAlt} fill loading="lazy" sizes="(max-width: 700px) 100vw, 70vw" /><button type="button" disabled={!permitted} onClick={() => setActive(true)}>{permitted ? "Videoyu oynat" : "Örnek video alanı"}</button></>}</div>{video.description && <p>{video.description}</p>}</section>;
}

function Gallery({ images }: { images: readonly ProjectImage[] }) {
  const [open, setOpen] = useState<number | null>(null);
  useEffect(() => { if (open === null) return; const close = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(null); if (event.key === "ArrowRight") setOpen((open + 1) % images.length); if (event.key === "ArrowLeft") setOpen((open - 1 + images.length) % images.length); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, [open, images.length]);
  if (!images.length) return null;
  return <section className="project-gallery" aria-labelledby="gallery-title"><h3 id="gallery-title">Proje galerisi</h3><div>{images.map((image, index) => <button type="button" key={`${image.src}-${image.order}`} onClick={() => setOpen(index)} aria-label={`${image.alt} görselini büyüt`}><Image src={assetPath(image.src)} alt={image.alt} fill loading="lazy" sizes="(max-width: 700px) 100vw, 33vw" /></button>)}</div>{open !== null && <div className="project-lightbox" role="dialog" aria-modal="true" aria-label="Proje görsel galerisi" onTouchEnd={(event) => { const start = Number(event.currentTarget.dataset.touchX ?? 0); const end = event.changedTouches[0]?.clientX ?? start; if (Math.abs(end - start) > 45) setOpen((open + (end < start ? 1 : -1) + images.length) % images.length); }} onTouchStart={(event) => { event.currentTarget.dataset.touchX = String(event.touches[0]?.clientX ?? 0); }}><button className="lightbox-close" type="button" onClick={() => setOpen(null)} aria-label="Galeriyi kapat">×</button><button type="button" onClick={() => setOpen((open - 1 + images.length) % images.length)} aria-label="Önceki görsel">←</button><figure><Image src={assetPath(images[open].src)} alt={images[open].alt} fill sizes="90vw" /></figure><button type="button" onClick={() => setOpen((open + 1) % images.length)} aria-label="Sonraki görsel">→</button></div>}</section>;
}

function ProjectDetail({ project, onClose }: { project: SectorProject; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { closeRef.current?.focus(); const close = (event: KeyboardEvent) => event.key === "Escape" && onClose(); document.addEventListener("keydown", close); document.body.classList.add("project-dialog-open"); return () => { document.removeEventListener("keydown", close); document.body.classList.remove("project-dialog-open"); }; }, [onClose]);
  return <div className="project-detail-overlay" role="dialog" aria-modal="true" aria-labelledby="project-detail-title"><article className="project-detail"><button ref={closeRef} className="project-detail-close" type="button" onClick={onClose} aria-label="Proje detayını kapat">×</button><div className="project-detail-cover"><Image src={assetPath(project.desktopCoverImage ?? project.coverImage)} alt={project.coverImageAlt} fill priority sizes="(max-width: 700px) 100vw, 80vw" /></div><span className="project-tag">{project.isPlaceholder ? "Örnek proje yerleşimi" : project.sector}</span><h2 id="project-detail-title">{project.title}</h2><p className="lead">{project.description}</p><dl className="project-facts"><div><dt>Sektör</dt><dd>{project.sector}</dd></div><div><dt>Ortam</dt><dd>{project.environment}</dd></div><div><dt>Şehir</dt><dd>{project.city}</dd></div><div><dt>Uygulama</dt><dd>{project.applicationType}</dd></div></dl><div className="project-detail-columns"><section><h3>Projenin ihtiyacı</h3><p>{project.summary}</p></section><section><h3>Önerilen LED ekran çözümü</h3><p>{project.products.join(", ")}</p></section><section><h3>Teknik kapsam</h3><ul>{project.technicalHighlights.map((item) => <li key={item}>{item}</li>)}</ul></section><section><h3>Montaj ve devreye alma</h3><ul>{project.services.map((item) => <li key={item}>{item}</li>)}</ul></section></div><Gallery images={project.galleryImages} />{project.videos.map((video) => <VideoPanel key={`${video.title}-${video.order}`} video={video} />)}<a className="button" href="/iletisim#teklif">Projenize Özel Teklif Al</a></article></div>;
}

export function ProjectShowcase({ projects, references }: { projects: readonly SectorProject[]; references: readonly ProjectReference[] }) {
  const [filters, setFilters] = useState<Filters>(emptyFilters);
  const [selected, setSelected] = useState<SectorProject | null>(null);
  const options = useMemo(() => ({ sectors: unique(projects.map((p) => p.sector)), environments: unique(projects.map((p) => p.environment)), products: unique(projects.flatMap((p) => p.products)), cities: unique(projects.map((p) => p.city)), applications: unique(projects.map((p) => p.applicationType)) }), [projects]);
  const filtered = useMemo(() => projects.filter((project) => (!filters.sector || project.sector === filters.sector) && (!filters.environment || project.environment === filters.environment) && (!filters.product || project.products.includes(filters.product)) && (!filters.city || project.city === filters.city) && (!filters.application || project.applicationType === filters.application)), [projects, filters]);
  if (!projects.length) return <section className="projects-empty"><span className="eyebrow">Doğrulanmış projeler</span><h2>Proje vitrini doğrulanmış kayıtlarla yayımlanır.</h2><p>Yayın ve görsel izni bulunmayan kayıtlar production ortamında gösterilmez.</p></section>;
  const select = (label: string, key: keyof Filters, values: string[]) => <label><span>{label}</span><select value={filters[key]} onChange={(event) => setFilters((current) => ({ ...current, [key]: event.target.value }))}><option value="">Tümü</option>{values.map((value) => <option key={value}>{value}</option>)}</select></label>;
  return <section className="project-showcase"><div className="project-showcase-heading"><span className="eyebrow">Proje vitrini</span><h2>Sektöre ve uygulamaya göre inceleyin</h2><p>Örnekler yalnız yerel geliştirme ortamında tasarım kontrolü amacıyla gösterilir.</p></div><form className="project-filter-panel" aria-label="Proje filtreleri" onSubmit={(event) => event.preventDefault()}>{select("Sektör", "sector", options.sectors)}{select("Ortam", "environment", options.environments)}{select("LED ekran türü", "product", options.products)}{select("Şehir", "city", options.cities)}{select("Uygulama", "application", options.applications)}<button type="button" onClick={() => setFilters(emptyFilters)}>Filtreleri temizle</button></form><p className="project-result" role="status" aria-live="polite">{filtered.length} proje kartı gösteriliyor.</p><div className="project-grid">{filtered.map((project) => <article key={project.id}><div className="project-card-image"><Image src={assetPath(project.coverImage)} alt={project.coverImageAlt} fill loading="lazy" sizes="(max-width: 700px) 100vw, 33vw" /></div><div className="project-card-copy"><span>{project.isPlaceholder ? "Örnek proje yerleşimi" : project.sector}</span><h3>{project.shortTitle}</h3><p>{project.sector} · {project.city} · {project.environment}</p><small>{project.products.join(", ")}</small><button type="button" onClick={() => setSelected(project)}>Projeyi inceleyin →</button></div></article>)}</div>{references.length > 0 && <section className="reference-showcase"><div><span className="eyebrow">Referanslar</span><h2>Logo ve proje bağlantısı için hazır yapı</h2></div><div className="reference-grid">{references.map((reference) => <article key={reference.id}>{reference.logo ? <Image src={assetPath(reference.logo)} alt={reference.logoAlt} width={180} height={80} loading="lazy" /> : <strong>Örnek logo alanı</strong>}<span>{reference.sector}</span></article>)}</div></section>}{selected && <ProjectDetail project={selected} onClose={() => setSelected(null)} />}</section>;
}
