import type { Metadata } from "next";
import { Breadcrumbs } from "@/components/breadcrumbs";
import { QuoteForm } from "@/components/quote-form";
import { site, whatsappUrl } from "@/lib/site";
export const metadata: Metadata = { title: "İletişim ve Teklif", description: "LED ekran projeniz için ölçü ve kullanım alanınızı paylaşın; LEDProje teknik ekibiyle WhatsApp veya telefon üzerinden görüşün.", alternates: { canonical: "/iletisim" } };
const mapsEmbedUrl = `https://www.google.com/maps?q=${encodeURIComponent(`${site.address.district}, ${site.address.street}, ${site.address.postalCode} ${site.address.locality}/${site.address.region}`)}&output=embed`;

export default function ContactPage() { return <><header className="page-hero page-hero-corporate page-hero-text-only"><div className="container"><Breadcrumbs current="İletişim ve Teklif" slug="iletisim" /><span className="eyebrow">Projenizi başlatın</span><h1>LED Ekran Projenizi Birlikte Netleştirelim</h1><p className="lead">Şehir, kullanım alanı ve ortam bilgisini paylaşın; teknik kapsamı birlikte netleştirelim.</p></div></header><section className="section"><div className="container contact-grid"><div id="teklif"><QuoteForm /></div><div className="prose contact-details"><span className="eyebrow">Doğrudan iletişim</span><h2>Teknik ön değerlendirme için ulaşın</h2><p><strong>Telefon</strong><br/><a className="text-link" href={site.phoneHref}>{site.phoneDisplay}</a></p><p><strong>WhatsApp</strong><br/><a className="text-link" href={whatsappUrl()} target="_blank" rel="noreferrer">Mesaj başlatın</a></p><div className="address-block"><strong>Adresimiz</strong><address>{site.addressFull}</address></div><div className="address-block"><strong>Çalışma Saatlerimiz</strong><p>{site.openingDays}&nbsp;&nbsp;|&nbsp;&nbsp;{site.opensAt} – {site.closesAt}</p><small className="hours-note">Resmî tatil günlerinde kapalı olabiliriz; ziyaret öncesi telefonla teyit almanızı öneririz.</small></div><div className="address-block"><strong>Hizmet bölgesi</strong><p>{site.serviceArea}</p></div><p><a className="text-link" href={site.mapsUrl} target="_blank" rel="noreferrer">Google Maps’te yol tarifi alın</a></p></div></div></section>
    <section className="section"><div className="container"><h2>Konum</h2><div className="map-embed"><iframe src={mapsEmbedUrl} width="100%" height="400" style={{ border: 0 }} allowFullScreen loading="lazy" title="LEDProje Konum" referrerPolicy="no-referrer-when-downgrade" /></div></div></section></>; }
