import type { SeoPage } from "@/lib/types";

type CitySeed = { city: string; priority: "P0" | "P1" | "P2"; intro: string; useTitle: string; uses: string; recommendation: string; faq: { question: string; answer: string } };
const seeds: CitySeed[] = [
  { city: "İstanbul", priority: "P0", intro: "İstanbul’daki mağaza, AVM, sergi alanı, kurumsal alan ve dış cephe projelerini keşif, entegrasyon, kendi teknik ekibimizle montaj ve servis bütünlüğünde ele alıyoruz.", useTitle: "Yoğun görüş alanlarında doğru ekran kararı", uses: "Vitrin ve cadde cephelerinde çevresel ışık; AVM ve sergi alanlarında yakın izleme; kurumsal yapılarda içerik kaynağı ve çalışma düzeni ayrı ayrı değerlendirilir.", recommendation: "Yakın izlenen mağaza ve sergi alanlarında iç mekân P1.86–P2.5; cephe ve açık alanlarda izleme mesafesine göre P3–P10 dış mekân seçenekleri teknik ön değerlendirmeye alınabilir.", faq: { question: "LEDProje İstanbul projelerini nasıl planlar?", answer: "İstanbul projeleri ölçü, kullanım ortamı ve saha koşulları üzerinden değerlendirilir. Kesin ziyaret veya keşif planı için önceden iletişim kurulmalıdır." } },
  { city: "Ankara", priority: "P0", intro: "Ankara’daki kurumsal toplantı alanı, showroom, mağaza ve bina cephesi ihtiyaçları için Türkiye geneli proje modelimiz kapsamında teknik ön değerlendirme, montaj ve devreye alma planlıyoruz.", useTitle: "Kurumsal sunumdan dış cephe görünürlüğüne", uses: "Toplantı ve konferans alanlarında yakın izleme ile kamera uyumu; showroom ve mağazalarda içerik okunurluğu; dış uygulamalarda parlaklık ve taşıyıcı koşullar öne çıkar.", recommendation: "Kurumsal iç mekânda izleme mesafesine göre P1.53–P3; dış cephe ve totem ihtiyaçlarında saha mesafesine göre P4, P5 veya P10 ailesi değerlendirilebilir.", faq: { question: "Ankara’da LEDProje şubesi var mı?", answer: "Hayır, Ankara’da fiziksel şube iddiamız yoktur. İstanbul merkezli ekibimiz Türkiye geneli hizmet modeliyle Ankara projelerini planlar." } },
  { city: "İzmir", priority: "P1", intro: "İzmir’de mağaza, showroom, otel, kurumsal alan ve açık hava uygulamalarına yönelik LED ekran projelerini kullanım ortamı ve saha koşulları üzerinden planlıyoruz.", useTitle: "İçeride yakın izleme, dışarıda çevresel koşullar", uses: "Perakende ve showroom projelerinde vitrin ışığı ile izleme mesafesi; otel ve kurumsal alanlarda mimari uyum; dış uygulamalarda cephe yönü ve bakım erişimi değerlendirilir.", recommendation: "Vitrin veya iç alanda poster ve P1.86–P2.5; cephe uygulamalarında doğru parlaklık, koruma sınıfı ve mesafeye göre P3–P10 seçenekleri karşılaştırılır.", faq: { question: "İzmir projesinde keşif nasıl planlanır?", answer: "Önce ölçü, görseller, kullanım ortamı ve izleme mesafesi alınır. Saha keşfi gereksinimi teknik ön değerlendirme sonrasında planlanır." } },
  { city: "Antalya", priority: "P1", intro: "Antalya’daki otel, karşılama alanı, mağaza, etkinlik mekânı ve dış cephe projelerinde ekranın çalışma ortamını, içerik akışını ve servis erişimini birlikte değerlendiriyoruz.", useTitle: "Konaklama ve karşılama alanlarında kesintisiz iletişim", uses: "Lobi ve karşılama alanlarında estetik entegrasyon, salonlarda görüş açısı, açık alanlarda parlaklık ve çevresel koruma proje kararını belirler.", recommendation: "Lobi ve salonlarda iç mekân ince pitch, yönlendirme ve kampanya için poster; açık alanlarda kaynak dokümanla doğrulanmış dış mekân ürün ailesi değerlendirilir.", faq: { question: "Antalya’da yerel servis noktanız var mı?", answer: "Antalya’da fiziksel servis noktası iddiamız yoktur. Teknik servis, Türkiye geneli hizmet planı kapsamında sistem ve saha bilgisine göre organize edilir." } },
  { city: "Bursa", priority: "P1", intro: "Bursa’daki showroom, sanayi tesislerinin iletişim alanı, mağaza ve kurumsal projeler için LED ekran sistemini ölçü, izleme mesafesi ve işletme düzenine göre tasarlıyoruz.", useTitle: "Showroom ve kurumsal alanlara teknik uyum", uses: "Ürün sunumu yapılan showroomlarda renk ve detay algısı, geniş kurumsal alanlarda görüş mesafesi, giriş ve dış cephede ise parlaklık ile konstrüksiyon öne çıkar.", recommendation: "Yakın ürün sunumunda P1.86–P2.5; daha geniş iç alanlarda P3–P4; dış giriş ve cephelerde saha mesafesine uygun piksel aralığı değerlendirilir.", faq: { question: "Bursa’daki mevcut altyapı değerlendirilebilir mi?", answer: "Evet. Güç, veri, taşıyıcı yüzey ve erişim bilgileri teknik ön değerlendirmeye dâhil edilir; uygunluk görülmeden varsayım yapılmaz." } },
  { city: "Konya", priority: "P1", intro: "Konya’daki showroom, kurumsal salon, mağaza, totem ve dış cephe LED ekran ihtiyaçlarını ürün tedarikinden mekanik montaj ve devreye almaya kadar sistem bütünlüğünde ele alıyoruz.", useTitle: "Geniş alanlarda izleme mesafesini merkeze almak", uses: "Showroom ve salonlarda ekranın en yakın ve ortalama izleme noktası; mağazada kampanya görünürlüğü; totem ve cephede açık alan görüş aksı değerlendirilir.", recommendation: "Geniş iç alanlarda P2.5–P4; totem uygulamalarında kaynak kapsamındaki P3–P5; daha uzak dış mekân görüşünde P5–P10 seçenekleri proje bazında incelenir.", faq: { question: "Konya projesi için sabit m² fiyatı veriliyor mu?", answer: "Hayır. Ölçüye ek olarak pitch, ortam, kabinet, kontrol, konstrüksiyon, montaj ve lojistik kapsamı netleştirilir." } },
  { city: "Kayseri", priority: "P1", intro: "Kayseri’deki mağaza, mobilya veya ürün showroomu, kurumsal alan ve dış mekân tanıtım projeleri için görüntü yüzeyi ile altyapıyı birlikte planlıyoruz.", useTitle: "Ürün sunumunda detay, dış alanda okunurluk", uses: "Showroomlarda yaklaşma mesafesi ve içerik detayı; mağazalarda vitrin yönü; dış alanlarda ekran yüksekliği, parlaklık ve bakım erişimi farklı kararlar gerektirir.", recommendation: "Detaylı ürün içeriklerinde P1.86 veya P2.5; orta mesafeli iç alanlarda P3–P4; totem ve cephede uygun outdoor ürün ailesi değerlendirilir.", faq: { question: "Kayseri’de montajı kim yapar?", answer: "Montaj ve devreye alma LEDProje’nin kendi teknik ekibi tarafından, Türkiye geneli proje planı kapsamında yürütülür." } },
  { city: "Samsun", priority: "P1", intro: "Samsun’daki mağaza, kurumsal alan, showroom ve dış mekân LED ekran projelerinde ürün seçimini kontrol, enerji, veri ve montaj koşullarıyla birlikte tasarlıyoruz.", useTitle: "Ekran konumuna göre sistem bütünlüğü", uses: "İç alanda görüş mesafesi ve içerik çözünürlüğü, vitrinlerde ışık koşulu, dış cephede koruma ve servis erişimi ön değerlendirmede ele alınır.", recommendation: "İç mekânda P1.86–P4 aralığı izleme mesafesine göre; dış mekânda P3–P10 aralığı ölçek ve görüş aksına göre incelenebilir.", faq: { question: "Samsun’a teknik servis sağlanıyor mu?", answer: "Evet, Türkiye geneli teknik servis kapsamında değerlendirme yapılır. Müdahale biçimi ve planı sistem bilgisi ile arıza kapsamı görülerek belirlenir." } },
  { city: "Erzurum", priority: "P2", intro: "Erzurum’daki iç ve dış mekân LED ekran projelerinde sıcaklık aralığı, kabinet koruması, erişim ve enerji altyapısı gibi saha kriterlerini ürün seçiminden önce değerlendiriyoruz.", useTitle: "Dış ortam koşullarını proje girdisine dönüştürmek", uses: "Açık alan uygulamalarında ekranın konumu, koruma seviyesi ve bakım erişimi; iç mekânda ise yakın izleme ve çalışma düzeni önceliklidir. Yerel koşullara ilişkin doğrulanmamış performans iddiası verilmez.", recommendation: "Kaynak dış mekân ailesi -20°C ~ +60°C çalışma aralığı ve ön IP65/arka IP54 verilerine sahiptir; nihai uygunluk saha ve ürün konfigürasyonuyla ayrıca doğrulanır.", faq: { question: "Soğuk hava için ürün uygunluğu nasıl belirlenir?", answer: "Kaynak teknik çalışma aralığı başlangıç verisidir. Kabinet, güç, erişim ve gerçek saha koşulları görülerek proje uygunluğu doğrulanır." } },
  { city: "Amasya", priority: "P2", intro: "Amasya’daki mağaza, kurumsal alan, salon ve dış cephe LED ekran ihtiyaçlarını gereksiz ölçek iddiası olmadan, kullanım amacına uygun sistem olarak projelendiriyoruz.", useTitle: "Alanı büyütmeden görünürlüğü doğru kurmak", uses: "Kompakt mağaza ve karşılama alanlarında yakın izleme ile fiziksel yerleşim; salonlarda görüş açısı; dış uygulamalarda cephe erişimi ve izleme noktası önemlidir.", recommendation: "Kompakt iç alanlarda P1.86–P2.5 veya poster çözümü; daha uzak iç/dış görüşte saha ölçüsüne uygun P3 ve üzeri seçenekler değerlendirilebilir.", faq: { question: "Amasya projesi uzaktan değerlendirilebilir mi?", answer: "Ölçü, fotoğraf, kullanım amacı ve izleme mesafesiyle teknik ön değerlendirme başlatılabilir. Gereken saha çalışması daha sonra planlanır." } },
];

const slugify = (city: string) => city.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/ı/g, "i").replace(/ş/g, "s").replace(/ğ/g, "g").replace(/ü/g, "u").replace(/ö/g, "o").replace(/ç/g, "c");
export const cityPages: SeoPage[] = seeds.map((seed) => ({
  slug: `${slugify(seed.city)}-led-ekran`, title: `${seed.city} LED Ekran Sistemleri`, description: `${seed.city} için profesyonel LED ekran sistemleri; projelendirme, montaj, devreye alma ve teknik servis. Projenize özel teklif alın.`, eyebrow: `${seed.priority} yerel öncelik · Türkiye geneli hizmet`, h1: `${seed.city} LED Ekran Sistemleri`, intro: seed.intro, primaryQuery: `${seed.city.toLocaleLowerCase("tr-TR")} led ekran`, kind: "city", index: true,
  sections: [
    { title: seed.useTitle, body: seed.uses },
    { title: `${seed.city} projesi için ürün yaklaşımı`, body: seed.recommendation, links: [{ href: "/ic-mekan-led-ekran", label: "İç mekân ürünleri" }, { href: "/dis-mekan-led-ekran", label: "Dış mekân ürünleri" }] },
    { title: "Keşif ve teknik ön değerlendirme", body: "Ölçü, en yakın izleme mesafesi, kullanım ortamı, içerik türü ve saha görselleri alınır. Gerekiyorsa keşif kapsamı belirlenir; doğrulanmayan saha bilgisi üretilmez.", links: [{ href: "/led-ekran-kesif-projelendirme", label: "Keşif ve projelendirme süreci" }] },
    { title: "Montaj, devreye alma ve servis modeli", body: `Türkiye geneli proje hizmeti kapsamında ${seed.city} montajı LEDProje’nin kendi teknik ekibiyle planlanır. Kabinet, güç ve veri bağlantıları, kontrol, hizalama, görüntü ayarı ve test tamamlanarak devreye alınır. Satış sonrası servis kapsamı proje verilerine göre yönetilir.`, links: [{ href: "/led-ekran-montaji", label: "Montaj ve devreye alma" }, { href: "/led-ekran-teknik-servis", label: "Teknik servis" }] },
    { title: `${seed.city} LED ekran fiyatı`, body: "Sabit ürün veya TL/m² fiyatı verilmez. Ölçü, pitch, ortam, kabinet, kontrol sistemi, konstrüksiyon, erişim, montaj, lokasyon ve lojistik net teklifi belirler.", links: [{ href: "/led-ekran-fiyatlari", label: "Fiyatı etkileyen faktörler" }, { href: "/led-ekran-metrekare-fiyati", label: "Ekran alanını hesaplayın" }] },
  ],
  faqs: [seed.faq, { question: `${seed.city} için hangi LED ekran seçilmeli?`, answer: "İç/dış ortam, ölçü ve izleme mesafesi bilinmeden tek ürün önerilmez. Bu bilgilerle pitch, parlaklık, kabinet ve kontrol gereksinimi çıkarılır." }, { question: `${seed.city} LED ekran fiyatı nasıl alınır?`, answer: "Ölçü, şehir, kullanım alanı ve iç/dış mekân bilgisini paylaşarak proje bazlı teklif sürecini başlatabilirsiniz." }],
  related: [{ href: "/led-ekranlar", label: "LED ekran sistemleri" }, { href: "/magaza-led-ekran", label: "Mağaza çözümleri" }, { href: "/dis-cephe-led-ekran", label: "Dış cephe çözümleri" }, { href: "/iletisim#teklif", label: `${seed.city} projesi için teklif alın` }],
}));
