import type { SeoPage } from "@/lib/types";
import { indoorCommon, indoorPitchRows, outdoorCommon, outdoorPitchRows } from "@/lib/technical-data";
import { cityPages } from "@/lib/cities";
import { pitchPages } from "@/lib/pitch-pages";

const quote = { href: "/iletisim#teklif", label: "Projenize özel teklif alın" };
const prices = { href: "/led-ekran-fiyatlari", label: "Fiyatlandırma yaklaşımı" };
const mounting = { href: "/led-ekran-montaji", label: "Montaj ve devreye alma" };
const commonFaq = [
  { question: "LED ekran için sabit fiyat verilebilir mi?", answer: "Hayır. Ölçü, piksel aralığı, kullanım ortamı, kabinet, kontrol sistemi, konstrüksiyon ve montaj koşulları birlikte değerlendirilir." },
  { question: "Türkiye geneline hizmet veriyor musunuz?", answer: "Evet. LEDProje, Türkiye genelindeki satış ve proje ihtiyaçları için teknik değerlendirme, montaj ve servis planlaması yapar." },
];

const pages: SeoPage[] = [
  {
    slug: "led-ekranlar", title: "LED Ekran Sistemleri", description: "İç ve dış mekân LED ekran sistemlerini, poster, esnek ve totem çözümlerini proje gereksiniminize göre karşılaştırın.", eyebrow: "Ürün ve sistem merkezi", h1: "Profesyonel LED Ekran Sistemleri", intro: "LED ekran yalnızca panellerden oluşmaz. Görüntü yüzeyi; kabinet, güç, veri, kontrol, mekanik taşıyıcı ve doğru yapılandırmayla birlikte çalışan bir sistemdir.", primaryQuery: "led ekran sistemleri", kind: "hub", index: true,
    sections: [
      { title: "Kullanım ortamına göre doğru sistem", body: "İç mekânda yakın izleme ve görüntü bütünlüğü; dış mekânda parlaklık, çevresel dayanım ve erişim koşulları öne çıkar. Poster, esnek ve totem sistemleri ise farklı fiziksel yerleşim ihtiyaçlarını karşılar.", links: [{ href: "/ic-mekan-led-ekran", label: "İç mekân sistemleri" }, { href: "/dis-mekan-led-ekran", label: "Dış mekân sistemleri" }] },
      { title: "Panelden devreye almaya sistem bütünlüğü", body: "Uygun LED panel/modül seçimi; projeye özel kabinet, güç kaynakları, enerji dağıtımı, alıcı kart, kontrol altyapısı, veri kablolaması ve mekanik uygulamayla tamamlanır. LEDProje bu bileşenleri proje hedefi etrafında entegre eder." },
      { title: "LED ekran paneli hangi anlama gelir?", body: "“LED ekran panel” ve “LED panel ekran” ifadeleri çoğu zaman ekran yüzeyini veya kabinet birimini tarif eder. Proje kararında tek bir panel yerine toplam sistem ölçüsü, çözünürlük, izleme mesafesi ve işletme koşulları değerlendirilmelidir." },
    ], faqs: commonFaq, related: [{ href: "/poster-led-ekran", label: "Poster LED ekran" }, { href: "/esnek-led-ekran", label: "Esnek LED ekran" }, { href: "/totem-led-ekran", label: "Totem LED ekran" }, quote],
  },
  {
    slug: "ic-mekan-led-ekran", title: "İç Mekân LED Ekran Sistemleri", description: "Mağaza, showroom, toplantı salonu ve kurumsal alanlar için yakın izlemeye uygun iç mekân LED ekran çözümleri.", eyebrow: "Yakın izleme · kontrollü ışık", h1: "İç Mekân LED Ekran Sistemleri", intro: "İç mekân projelerinde piksel aralığı, izleme mesafesi ve içerik türü birlikte ele alınır. Amaç yalnız parlak bir yüzey değil, doğru mesafeden bütünlüklü ve okunaklı görüntüdür.", primaryQuery: "iç mekan led ekran", kind: "product", index: true, specs: indoorPitchRows,
    sections: [
      { title: "Yakın izleme için piksel aralığı seçimi", body: "P1.53 ve P1.86 gibi daha sık piksel yapıları yakın izleme gereken alanlara; P2.5, P3 ve P4 seçenekleri ise mesafe ve ekran ölçeğine göre farklı projelere yönelir. Nihai seçim, saha ölçüsü ve içerik hedefiyle doğrulanır.", bullets: indoorCommon },
      { title: "İç mekân LED ekran fiyatları", body: "Fiyat; yalnız m² üzerinden oluşmaz. Toplam çözünürlük, pitch, kabinet yapısı, kontrol sistemi, taşıyıcı uygulama, enerji/data hattı ve montaj koşulları proje bedelini birlikte belirler.", links: [prices, { href: "/led-ekran-metrekare-fiyati", label: "Alan hesaplama aracı" }] },
      { title: "Mağazadan toplantı salonuna", body: "Vitrin arkası, showroom, lobi, konferans ve kurumsal sunum alanlarında içerik okunurluğu ve bakım erişimi farklılaşır. Projelendirme bu kullanım akışına göre yapılır." },
    ], faqs: [{ question: "İç mekân LED ekranda en iyi pitch hangisidir?", answer: "Tek bir doğru pitch yoktur. En yakın izleme mesafesi, ekran ölçüsü, içerik çözünürlüğü ve bütçe birlikte değerlendirilmelidir." }, ...commonFaq], related: [{ href: "/p2-5-led-ekran", label: "P2.5 LED ekran" }, { href: "/magaza-led-ekran", label: "Mağaza çözümleri" }, mounting, quote],
  },
  {
    slug: "dis-mekan-led-ekran", title: "Dış Mekân LED Ekran Sistemleri", description: "Yüksek parlaklık, çevresel koruma ve saha koşullarına göre projelendirilen profesyonel dış mekân LED ekran sistemleri.", eyebrow: "Yüksek parlaklık · saha dayanımı", h1: "Dış Mekân LED Ekran Sistemleri", intro: "Dış mekân LED ekran projelerinde görünürlük kadar kabinet, koruma sınıfı, taşıyıcı sistem, enerji dağıtımı ve servis erişimi de sistem kararının parçasıdır.", primaryQuery: "dış mekan led ekran", kind: "product", index: true, specs: outdoorPitchRows,
    sections: [
      { title: "Gün ışığında görünürlük ve koruma", body: "Kaynak teknik verilere göre dış mekân ailesi yaklaşık 5.500–6.500 nit parlaklık, ön IP65 ve arka IP54 koruma sunar. Gerçek proje seçimi cephe yönü, izleme mesafesi ve erişim koşullarıyla doğrulanır.", bullets: outdoorCommon },
      { title: "Dış mekân LED ekran fiyatları", body: "Pixel pitch ve toplam alanın yanı sıra kabinet, çelik konstrüksiyon, erişim ekipmanı, enerji/data altyapısı, lokasyon ve montaj planı fiyat üzerinde belirleyicidir. Bu nedenle sabit ürün veya m² fiyatı gösterilmez.", links: [prices] },
      { title: "Ürün kategorisi ile cephe uygulaması arasındaki fark", body: "Bu sayfa dış mekân ürün ailesini ve teknik seçim kriterlerini açıklar. Bina cephesine özel konstrüksiyon, erişim ve mimari entegrasyon için dış cephe çözüm sayfası kullanılmalıdır.", links: [{ href: "/dis-cephe-led-ekran", label: "Dış cephe LED ekran projeleri" }] },
    ], faqs: [{ question: "Outdoor LED ekran hangi pitch seçeneklerinde sunulur?", answer: "Kaynak teknik kapsam P2.5, P3, P4, P5 ve P10 seçeneklerini içerir. Uygun pitch izleme mesafesine ve uygulama ölçeğine göre belirlenir." }, ...commonFaq], related: [{ href: "/p5-led-ekran", label: "P5 LED ekran" }, { href: "/p10-led-ekran", label: "P10 LED ekran" }, mounting, quote],
  },
  {
    slug: "poster-led-ekran", title: "Poster LED Ekran Sistemleri", description: "Mağaza, showroom ve karşılama alanları için P1.86, P2.5 ve P3 poster LED ekran sistemleri.", eyebrow: "Dikey dijital iletişim", h1: "Poster LED Ekran Sistemleri", intro: "Poster LED ekran; dikey içerik akışı gereken mağaza, showroom ve karşılama noktalarında hareketli kampanya ve ürün iletişimi için planlanır.", primaryQuery: "poster led ekran", kind: "product", index: true,
    sections: [{ title: "Dikey format için doğru içerik yüzeyi", body: "Poster sistemlerinde ekran konumu, yaklaşma mesafesi ve içerik oranı birlikte planlanır. Kaynak teknik kapsam P1.86, P2.5 ve P3 seçeneklerini içerir." }, { title: "Tekli veya çoklu yerleşim", body: "Birden fazla poster ekranın kullanıldığı projelerde içerik senkronizasyonu, elektrik/data dağıtımı ve mekândaki yaya akışı değerlendirilir." }, { title: "Proje fiyatını belirleyenler", body: "Pitch, adet, kontrol senaryosu, taşıyıcı biçimi, montaj ve içerik yönetimi gereksinimi teklif kapsamını oluşturur.", links: [prices] }], faqs: [{ question: "Poster LED ekran nerede kullanılır?", answer: "Mağaza girişi, vitrin yakını, showroom, fuaye ve kurumsal karşılama gibi dikey içerik gereken alanlarda değerlendirilebilir." }, ...commonFaq], related: [{ href: "/magaza-led-ekran", label: "Mağaza LED ekran" }, { href: "/led-ekran-kontrol-sistemleri", label: "Kontrol sistemleri" }, quote],
  },
  {
    slug: "esnek-led-ekran", title: "Esnek LED Ekran Sistemleri", description: "Kavisli ve özel yüzeyler için P1.86 ve P2.5 esnek LED ekran çözümleri; projelendirme, montaj ve devreye alma.", eyebrow: "Kavisli yüzey · özel geometri", h1: "Esnek LED Ekran Sistemleri", intro: "Esnek LED ekran sistemleri, düz bir kabinet diziliminin karşılayamadığı kavisli veya özel geometrili iç mekân yüzeyleri için değerlendirilir.", primaryQuery: "esnek led ekran", kind: "product", index: true,
    sections: [{ title: "Yüzeye göre mekanik tasarım", body: "Esnek modül tek başına proje değildir. Yarıçap, taşıyıcı yüzey, modül yerleşimi, kablo rotası ve bakım erişimi birlikte çözümlenir." }, { title: "Doğrulanmış pitch kapsamı", body: "Kaynak dokümanda esnek ürün ailesi için P1.86 ve P2.5 seçenekleri yer alır. Proje sınırları uygulama geometrisi üzerinden doğrulanır." }, { title: "İçerik ve görüntü sürekliliği", body: "Kavis boyunca görüntünün bozulmaması için içerik tasarım alanı, kontrol sistemi ve fiziksel modül hizalaması koordineli yürütülür." }], faqs: [{ question: "Esnek LED ekran her eğri yüzeye uygulanabilir mi?", answer: "Hayır. Uygulanabilir yarıçap ve mekanik sınırlar ürün ve proje detaylarıyla doğrulanmalıdır; doğrulanmadan teknik değer taahhüt edilmez." }, ...commonFaq], related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân LED ekran" }, { href: "/p2-5-led-ekran", label: "P2.5 LED ekran" }, quote],
  },
  {
    slug: "totem-led-ekran", title: "Totem LED Ekran Sistemleri", description: "P3, P4 ve P5 totem LED ekranlar için saha, taşıyıcı, kontrol ve montaj odaklı anahtar teslim proje yaklaşımı.", eyebrow: "Dikey dış mekân görünürlüğü", h1: "Totem LED Ekran Sistemleri", intro: "Totem LED ekran; ekran yüzeyi, dış gövde, taşıyıcı temel, enerji/data erişimi ve bakım senaryosunun tek sistem olarak ele alındığı bir dış mekân uygulamasıdır.", primaryQuery: "totem led ekran", kind: "product", index: true,
    sections: [{ title: "P3, P4 ve P5 seçenekleri", body: "Kaynak kapsamındaki pitch alternatifleri, izleme mesafesi ve totemin sahadaki konumuna göre değerlendirilir. Daha sık pitch her proje için otomatik olarak daha doğru değildir." }, { title: "Gövde ve taşıyıcı sistem", body: "Rüzgâr ve statik hesaplar yetkili proje disiplinlerinin doğrulamasını gerektirir. LEDProje ekran entegrasyonu, kabinet, enerji/data ve montaj koordinasyonunu proje kapsamına göre yönetir." }, { title: "İçerik kontrolü ve servis erişimi", body: "Senkron veya asenkron yayın ihtiyacı, bağlantı altyapısı ve bakım erişimi saha keşfinde belirlenir." }], faqs: [{ question: "Totem LED ekran için temel gerekir mi?", answer: "Saha ve taşıyıcı çözümüne göre gerekebilir. Statik ve uygulama detayları proje bazında yetkili disiplinlerce doğrulanmalıdır." }, ...commonFaq], related: [{ href: "/dis-mekan-led-ekran", label: "Dış mekân LED ekran" }, { href: "/p4-led-ekran", label: "P4 LED ekran" }, quote],
  },
  {
    slug: "led-ekran-kontrol-sistemleri", title: "LED Ekran Kontrol Sistemleri", description: "Sender, receiver, controller, senkron ve asenkron yayın yapıları için projeye uygun LED ekran kontrol sistemi entegrasyonu.", eyebrow: "Görüntü ve data yönetimi", h1: "LED Ekran Kontrol Sistemleri", intro: "Kontrol sistemi; kaynaktaki görüntünün ekran yüzeyine doğru çözünürlük, tarama ve zamanlama ile aktarılmasını sağlar. Seçim ekran çözünürlüğüne ve yayın senaryosuna göre yapılır.", primaryQuery: "led ekran kontrol sistemleri", kind: "technical", index: true,
    sections: [{ title: "Sender, receiver ve controller yapısı", body: "Sender/controller görüntü kaynağını işler; receiver kartlar kabinet ve modül dağılımına göre veriyi ekrana taşır. Kart sayısı ve bağlantı topolojisi proje çözünürlüğüyle hesaplanır." }, { title: "Senkron ve asenkron yayın", body: "Canlı HDMI kaynağı gereken projelerde senkron; planlı içerik oynatma gereken uygun projelerde asenkron yapı değerlendirilebilir. Uzaktan yönetim ancak bağlantı ve güvenlik gereksinimleri doğrulandığında planlanır." }, { title: "Konfigürasyon ve devreye alma", body: "Data hattı, mapping, ekran çözünürlüğü, parlaklık ve görüntü ayarları montaj sonrası test edilerek devreye alınır." }], faqs: [{ question: "Kontrol sistemi ekrandan ayrı seçilebilir mi?", answer: "Kontrol kapasitesi toplam piksel yükü, giriş kaynakları ve yayın biçimiyle uyumlu olmalıdır; bağımsız bir aksesuar gibi seçilmemelidir." }, ...commonFaq], related: [{ href: "/led-ekranlar", label: "LED ekran sistemleri" }, mounting, quote],
  },
  {
    slug: "led-ekran-fiyatlari", title: "LED Ekran Fiyatları Nasıl Belirlenir?", description: "LED ekran fiyatlarını belirleyen ölçü, pixel pitch, kabinet, kontrol, konstrüksiyon ve montaj unsurlarını öğrenin; proje teklifi alın.", eyebrow: "Proje maliyeti rehberi", h1: "LED Ekran Fiyatları Nasıl Belirlenir?", intro: "Profesyonel LED ekran fiyatı sabit bir ürün etiketinden değil, ekran yüzeyiyle birlikte çalışan teknik ve mekanik sistemin toplamından oluşur. Bu sayfada rakam vermeden teklif kapsamını şeffaflaştırıyoruz.", primaryQuery: "led ekran fiyatları", kind: "solution", index: true,
    sections: [
      { title: "Ekran ölçüsünün fiyata etkisi", body: "En ve boy toplam modül/kabinet adedini, çözünürlüğü, güç ihtiyacını ve taşıyıcı sistemi etkiler. Ölçü yalnız alanı değil, sistem geometrisini de belirler." },
      { title: "Piksel aralığı maliyeti nasıl değiştirir?", body: "Daha sık piksel aralığı aynı alanda daha fazla piksel ve farklı kontrol kapasitesi anlamına gelir. Doğru karar en yakın izleme mesafesi ve içerik hedefiyle verilir." },
      { title: "İç ve dış mekân maliyet farkları", body: "Dış mekân görünürlüğü, çevresel koruma, kabinet, konstrüksiyon ve erişim koşulları; iç mekânda ise yakın izleme ve mimari entegrasyon farklı maliyet bileşenleri oluşturur." },
      { title: "Kabinet, konstrüksiyon ve erişim", body: "Projeye özel kabinet/kasa, taşıyıcı sistem, cephe erişimi ve montaj ekipmanı teklif kapsamına göre hesaplanır. Statik gereklilikler ilgili uzmanlıklarla doğrulanır." },
      { title: "Kontrol, enerji ve veri altyapısı", body: "Kontrol sistemi kapasitesi, alıcı kart dağılımı, güç kaynakları, enerji panosu ve kablolama sistemin büyüklüğüne ve kullanım senaryosuna göre boyutlandırılır." },
      { title: "Montaj, devreye alma ve teknik servis", body: "Lokasyon, lojistik, saha çalışma koşulları, modül hizalama, görüntü ayarı, test ve servis kapsamı toplam proje fiyatına dahildir." },
      { title: "Projenize özel fiyat nasıl hesaplanır?", body: "En, boy, şehir, iç/dış mekân ve kullanım alanını paylaşın. Teknik ekip izleme mesafesi ile saha koşullarını netleştirerek uygun sistem kapsamını çıkarır.", links: [{ href: "/iletisim#teklif", label: "Teklif bilgilerini gönderin" }, { href: "/led-ekran-metrekare-fiyati", label: "Ekran alanını hesaplayın" }] },
    ], faqs: [{ question: "Neden web sitesinde TL veya m² fiyatı yok?", answer: "Aynı alandaki iki ekran; pitch, ortam, kabinet, kontrol, konstrüksiyon ve montaj açısından farklı sistemler olabilir. Doğrulanmamış bir rakam yanıltıcı olacağı için fiyat proje verileriyle hesaplanır." }, ...commonFaq], related: [{ href: "/led-ekran-metrekare-fiyati", label: "Metrekare fiyatı ve alan hesabı" }, { href: "/ic-mekan-led-ekran", label: "İç mekân fiyat faktörleri" }, { href: "/dis-mekan-led-ekran", label: "Dış mekân fiyat faktörleri" }, quote],
  },
  {
    slug: "led-ekran-metrekare-fiyati", title: "LED Ekran Metrekare Fiyatı ve Alan Hesabı", description: "LED ekran alanınızı en ve boy ölçüsüyle hesaplayın; m² fiyatının neden tek başına proje bedelini belirlemediğini öğrenin.", eyebrow: "Alan hesabı · teklif başlangıcı", h1: "LED Ekran Metrekare Fiyatı Nasıl Hesaplanır?", intro: "Ekran alanı en × boy formülüyle hesaplanır. Fakat m² yalnız fiziksel büyüklüğü gösterir; net fiyat için pitch, ortam, kabinet, kontrol, konstrüksiyon ve montaj bilgileri gerekir.", primaryQuery: "led ekran metrekare fiyatı", kind: "solution", index: true,
    sections: [{ title: "Aynı m², neden farklı proje?", body: "P2.5 ve P5 ekran aynı fiziksel alana sahip olsa bile toplam piksel sayısı, ideal izleme mesafesi ve kontrol yükü aynı değildir. İç/dış mekân koruması ve parlaklık gereksinimi de sistem kapsamını değiştirir." }, { title: "m² hesabına eklenen proje bileşenleri", body: "Kabinet geometrisi, taşıyıcı konstrüksiyon, controller/receiver yapısı, güç ve data dağıtımı, saha erişimi, lojistik, montaj ve devreye alma net teklifte değerlendirilir." }, { title: "Genel fiyat rehberinden farkı", body: "Bu sayfa alan ve m² hesaplama beklentisini karşılar. Toplam proje maliyetini etkileyen tüm kalemlerin ayrıntılı açıklaması ayrı fiyat rehberindedir.", links: [prices] }], faqs: [{ question: "LED ekran alanı nasıl hesaplanır?", answer: "Metre cinsinden en ile boy çarpılır. Örneğin 6 m × 3 m ekran alanı 18 m²’dir; bu sonuç fiyat değildir." }, ...commonFaq], related: [prices, { href: "/p2-5-led-ekran", label: "P2.5 ve piksel yoğunluğu" }, { href: "/p5-led-ekran", label: "P5 ve izleme mesafesi" }, quote],
  },
  {
    slug: "magaza-led-ekran", title: "Mağaza LED Ekran Çözümleri", description: "Vitrin, iç alan ve kampanya iletişimi için mağazaya özel LED ekran projelendirme, montaj ve içerik altyapısı.", eyebrow: "Perakende görünürlüğü", h1: "Mağaza LED Ekran Çözümleri", intro: "Mağaza LED ekranı, ürün kategorisinden çok müşteri akışı ve iletişim hedefiyle şekillenen bir kullanım senaryosudur. Vitrin, giriş ve iç alan için farklı çözüm gerekir.", primaryQuery: "mağaza led ekran", kind: "solution", index: true,
    sections: [{ title: "Vitrin ve iç alanı ayrı değerlendirin", body: "Vitrin arkasında gün ışığı, cam yansıması ve dışarıdan izleme; iç alanda ise yakın mesafe, içerik detayı ve mimari uyum önem kazanır." }, { title: "Pitch ve yerleşim", body: "Yakın izlenen ürün iletişiminde daha sık pitch seçenekleri değerlendirilir. Ekran yüksekliği ve bakış açısı, içerik okunurluğu için ölçüyle birlikte planlanır." }, { title: "Kampanya yönetimi ve kontrol", body: "Tek mağaza veya birden fazla ekran için içerik kaynağı, yayın sıklığı ve uzaktan yönetim gereksinimi proje aşamasında tanımlanır." }], faqs: [{ question: "Mağaza vitrini için iç mekân ekran kullanılabilir mi?", answer: "Konum, doğrudan ışık, cam yansıması ve çevresel koşullar görülmeden karar verilmemelidir. Teknik ön değerlendirme uygun parlaklık ve ürün ailesini belirler." }, ...commonFaq], related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân ürün kategorisi" }, { href: "/poster-led-ekran", label: "Poster LED ekran" }, prices, quote],
  },
  {
    slug: "dis-cephe-led-ekran", title: "Dış Cephe LED Ekran Projeleri", description: "Bina cepheleri için LED ekran; konstrüksiyon, erişim, enerji, data, montaj ve devreye alma odaklı proje çözümü.", eyebrow: "Mimari ve mekanik entegrasyon", h1: "Dış Cephe LED Ekran Projeleri", intro: "Dış cephe LED ekran, bir ürün seçiminin ötesinde bina yüzeyi, taşıyıcı konstrüksiyon, erişim, enerji/data ve servis planının birlikte çözüldüğü uygulama projesidir.", primaryQuery: "dış cephe led ekran", kind: "solution", index: true,
    sections: [{ title: "Cepheye özel saha değerlendirmesi", body: "Cephe yönü, ekran kotu, izleme aksı, montaj erişimi ve bakım yaklaşımı ölçülmeden sistem kesinleştirilmez." }, { title: "Konstrüksiyon ve entegrasyon", body: "Ekran kabinetleri ile bina arasındaki mekanik arayüz projeye özel çözülür. Gerekli statik ve yapısal doğrulamalar ilgili yetkin disiplinlerin kapsamındadır." }, { title: "Dış mekân ürün kategorisinden farkı", body: "Dış mekân sayfası parlaklık, IP ve pitch gibi ürün kriterlerini açıklar. Bu sayfa ise bina cephesi uygulamasının saha, mekanik ve operasyon kapsamına odaklanır.", links: [{ href: "/dis-mekan-led-ekran", label: "Dış mekân ürün kriterleri" }] }], faqs: [{ question: "Cephe LED ekranında keşif neden gereklidir?", answer: "Ölçü, kot, görüş açısı, güç/data rotası, taşıyıcı yüzey ve erişim koşulları proje kapsamını doğrudan etkiler." }, ...commonFaq], related: [{ href: "/dis-mekan-led-ekran", label: "Dış mekân LED ekran" }, mounting, { href: "/led-ekran-kesif-projelendirme", label: "Keşif ve projelendirme" }, quote],
  },
  {
    slug: "avm-led-ekran", title: "AVM LED Ekran Çözümleri", description: "AVM girişleri, ortak alanlar, yönlendirme ve kampanya iletişimi için profesyonel LED ekran sistem entegrasyonu.", eyebrow: "Ortak alan iletişimi", h1: "AVM LED Ekran Çözümleri", intro: "AVM projelerinde ekran; ziyaretçi akışı, izleme mesafesi, mimari yüzey, çalışma saatleri ve içerik yönetimiyle birlikte planlanır.", primaryQuery: "avm led ekran", kind: "solution", index: true,
    sections: [{ title: "Giriş, atrium ve ortak alan", body: "Her noktanın görüş açısı ve yaklaşma mesafesi farklıdır. Büyük yüzey, dikey poster veya kavisli ekran seçimi yerleşime göre yapılır." }, { title: "Operasyonla uyumlu montaj", body: "Saha erişimi, çalışma zamanları, enerji/data hattı ve güvenli montaj planı AVM yönetimiyle koordinasyon gerektirebilir." }, { title: "İçerik kontrolü", body: "Canlı kaynak, planlı kampanya veya çoklu ekran senaryosu; uygun kontrol sistemi ve data topolojisiyle hazırlanır." }], faqs: [{ question: "AVM için tek bir LED ekran tipi var mı?", answer: "Hayır. İç/dış konum, izleme mesafesi, ekran biçimi ve içerik akışı farklı ürün ve kontrol yapılarına yöneltebilir." }, ...commonFaq], related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân LED ekran" }, { href: "/esnek-led-ekran", label: "Esnek LED ekran" }, mounting, quote],
  },
];

const servicePages: SeoPage[] = [
  ["led-ekran-kesif-projelendirme", "LED Ekran Keşif ve Projelendirme", "led ekran keşif ve projelendirme", "Doğru sistem; ölçü, izleme mesafesi, ortam ve operasyon ihtiyacı netleştirilerek başlar.", ["İhtiyaç ve kullanım senaryosu", "Ölçü, izleme aksı ve saha koşulları", "Pitch, kabinet, kontrol ve taşıyıcı kapsamı"]],
  ["led-ekran-montaji", "LED Ekran Montajı ve Devreye Alma", "led ekran montajı", "LEDProje’nin kendi teknik ekibi, mekanik montajdan görüntü ayarı ve teste kadar devreye alma sürecini yürütür.", ["Taşıyıcı ve kabinet montajı", "Güç ve data kablolaması", "Modül hizalama, konfigürasyon ve test"]],
  ["led-ekran-bakim-onarim", "LED Ekran Bakım ve Onarım", "led ekran bakım onarım", "Planlı bakım ve arıza değerlendirmesi; sistem yapısı, erişim koşulları ve değişmesi gereken bileşenlere göre ele alınır.", ["Görsel ve fiziksel kontrol", "Güç, data ve modül değerlendirmesi", "Müdahale kapsamının proje bazında planlanması"]],
  ["led-ekran-teknik-servis", "LED Ekran Teknik Servis", "led ekran teknik servis", "Satış sonrası teknik servis LEDProje tarafından sağlanır; servis kapsamı sistem ve saha verileriyle belirlenir.", ["Arıza bilgisinin alınması", "Uzaktan ön değerlendirme", "Gerektiğinde planlı saha müdahalesi"]],
].map(([slug, h1, primaryQuery, intro, bullets]) => ({ slug, title: h1, description: `${h1} için LEDProje teknik yaklaşımı, süreç kapsamı ve proje bazlı destek.`, eyebrow: "Profesyonel hizmet", h1, intro, primaryQuery, kind: "service", index: true, sections: [{ title: "Süreç nasıl ilerler?", body: "Teknik kapsam, mevcut sistem bilgisi ve saha koşulları alınarak netleştirilir. Doğrulanmayan süre veya sonuç taahhüdü verilmez.", bullets }, { title: "Sistem bütünlüğü", body: "Panel/modül, kabinet, güç, receiver/data, kontrol ve mekanik bileşenler birbirinden bağımsız değil, çalışan sistem bütünü içinde değerlendirilir." }, { title: "Teklif ve planlama", body: "Şehir, ölçü, kullanım ortamı ve mevcut altyapı bilgileriyle teknik ön değerlendirme başlatılır.", links: [quote] }], faqs: commonFaq, related: [{ href: "/led-ekranlar", label: "LED ekran sistemleri" }, prices, quote] })) as SeoPage[];

const corporatePages: SeoPage[] = [
  { slug: "teknik-bilgi", title: "LED Ekran Teknik Bilgi Merkezi", description: "Pixel pitch, izleme mesafesi, parlaklık, IP koruma ve kontrol sistemleri için teknik başlangıç rehberi.", eyebrow: "Karar destek merkezi", h1: "LED Ekran Teknik Bilgi", intro: "Proje kararını etkileyen kavramları satış diliyle değil, kullanım sonucuyla ilişkilendirerek açıklıyoruz.", primaryQuery: "led ekran teknik bilgi", kind: "hub", index: true, sections: [{ title: "Pixel pitch ve izleme mesafesi", body: "Pitch, komşu piksellerin merkezleri arasındaki milimetre mesafesidir. Daha düşük değer daha sık piksel demektir; seçim en yakın izleme mesafesine göre yapılır.", links: [{ href: "/p2-5-led-ekran", label: "P2.5 rehberi" }, { href: "/p4-led-ekran", label: "P4 rehberi" }, { href: "/p5-led-ekran", label: "P5 rehberi" }, { href: "/p10-led-ekran", label: "P10 rehberi" }] }, { title: "Nit, IP ve çalışma ortamı", body: "Parlaklık çevresel ışıkla; IP koruma ise ekipmanın toz ve suya karşı koruma seviyesiyle ilgilidir. İç ve dış mekân ürünleri bu yüzden aynı kapsamda değerlendirilmez." }, { title: "Kontrol sistemi nasıl çalışır?", body: "Görüntü kaynağı controller/sender üzerinden receiver kartlara, oradan kabinet ve modüllere dağıtılır.", links: [{ href: "/led-ekran-kontrol-sistemleri", label: "Kontrol sistemi detayları" }] }], faqs: commonFaq, related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân teknik verileri" }, { href: "/dis-mekan-led-ekran", label: "Dış mekân teknik verileri" }, quote] },
  { slug: "hakkimizda", title: "Hakkımızda", description: "2021’den bu yana LED ekran üreticisi olarak iç mekân, dış mekân, poster, esnek ve totem LED ekran imalatı; projelendirme, montaj ve teknik servis.", eyebrow: "LEDProje", h1: "2021’den Bu Yana LED Ekran Üreticisiyiz", intro: "LEDProje, 2021 yılında kurulan; iç mekân, dış mekân, poster, esnek ve totem LED ekran sistemlerini kendi imalatıyla üreten, projelendiren, kuran ve satış sonrası teknik servisini yürüten İstanbul merkezli bir LED ekran üreticisidir.", primaryQuery: "LEDProje", kind: "corporate", index: true, sections: [{ title: "Üretici ve sistem entegratörü", body: "LED modül ve kabinet imalatından projeye özel güç, veri, kontrol ve mekanik uygulamaya kadar bileşenleri kendi üretim ve proje sürecimizde tek hedef etrafında birleştiririz. Ürün 320 × 160 mm modül ve alüminyum kabinet yapısıyla, ön veya arka bakıma uygun biçimde üretilir." }, { title: "Kendi teknik ekibimizle saha uygulaması", body: "Montaj, modül hizalama, sistem yapılandırması, görüntü ayarı, test ve devreye alma LEDProje teknik ekibi tarafından yürütülür. Donanım arızaları kendi imalat atölyemizde onarılır; yazılımsal sorunlarda uzaktan destek verilir." }, { title: "İstanbul’dan Türkiye geneline", body: "Türkiye genelindeki projelere satış, montaj ve teknik servis hizmeti planlarız; başka şehirlerde fiziksel şube iddiasında bulunmayız." }], faqs: commonFaq, related: [{ href: "/led-ekran-kesif-projelendirme", label: "Proje yaklaşımımız" }, mounting, quote] },
  { slug: "projeler", title: "LED Ekran Projeleri", description: "Tamamlanan LED ekran projelerimiz: her çalışma için ekran tipi, kurulum ortamı ve uygulama detayları, müşteri kullanım izniyle paylaşılır.", eyebrow: "Referans projelerimiz", h1: "Tamamlanan LED Ekran Projeleri", intro: "Aşağıda yer alan projeler müşterilerimizin kullanım izniyle paylaşılmaktadır. Her proje için ekran tipi, kurulum ortamı ve uygulama detayları belirtilmiştir.", ctaNote: "Projenizi görüşmek için teklif alabilir ya da doğrudan bizi arayabilirsiniz.", primaryQuery: "led ekran projeleri", kind: "corporate", index: true, sections: [], faqs: [], related: [{ href: "/led-ekranlar", label: "Sistemleri inceleyin" }, quote] },
  {
    slug: "cerez-politikasi", title: "Çerez Politikası", description: "LEDProje web sitesinde kullanılan çerezler, kullanım amaçları, saklama süreleri ve çerez tercihinizi nasıl değiştirebileceğiniz.", eyebrow: "Kişisel verilerin korunması", h1: "Çerez Politikası", intro: "Bu politika, ledproje.com.tr adresinde hangi çerezlerin kullanıldığını, hangi amaçla işlendiğini ve tercihinizi nasıl yönetebileceğinizi açıklar.", primaryQuery: "ledproje çerez politikası", kind: "corporate", index: true,
    sections: [
      { title: "Kullanılan çerezler", body: "Sitede yalnız trafik ölçümü amacıyla Google Analytics 4 çerezleri kullanılır. Sitenin çalışması için gerekli olan teknik çerezler dışında reklam, profilleme veya üçüncü taraf pazarlama çerezi kullanılmaz.", bullets: ["_ga — ziyaretçiyi ayırt etmek için kullanılır, tarayıcıda 2 yıl saklanır.", "_ga_5735NEXF3V — oturum durumunu korumak için kullanılır, tarayıcıda 2 yıl saklanır.", "ledproje_consent — çerez tercihinizi hatırlamak için kullanılır, 1 yıl saklanır ve ölçümleme amacı taşımaz."] },
      { title: "İşleme amacı", body: "Analitik çerezler; hangi sayfaların görüntülendiğini, ziyaretin hangi kanaldan geldiğini ve sayfa içi etkileşimleri (teklif formu, WhatsApp yönlendirmesi, alan hesaplama) toplu ve anonim biçimde ölçmek için kullanılır. Amaç site içeriğini ve kullanılabilirliğini geliştirmektir; kişiye özel profil oluşturulmaz." },
      { title: "Saklama süresi", body: "Google Analytics 4 üzerinde olay ve kullanıcı verisi 14 ay saklanır, bu sürenin sonunda otomatik olarak silinir. Çerezlerin tarayıcınızdaki ömrü yukarıdaki tabloda belirtilmiştir; tarayıcı verilerini temizlediğinizde çerezler de silinir." },
      { title: "Hukuki dayanak", body: "Zorunlu teknik çerezler, 6698 sayılı Kişisel Verilerin Korunması Kanunu madde 5/2 kapsamında meşru menfaat ve sözleşmenin ifası hukuki sebeplerine dayanır ve açık rıza gerektirmez. Analitik çerezler ise yalnız açık rızanız alındıktan sonra çalıştırılır; onay vermediğiniz sürece ölçümleme çerezi yazılmaz." },
      { title: "Tercihinizi nasıl değiştirirsiniz?", body: "Siteye ilk girişte görünen çerez bandından “Reddet” seçeneğini kullanabilirsiniz. Kararınızı sonradan değiştirmek isterseniz sayfa altındaki “Çerez tercihleri” bağlantısıyla bandı yeniden açabilirsiniz. Ayrıca tarayıcınızın ayarlar bölümünden çerezleri tümüyle engelleyebilir veya mevcut çerezleri silebilirsiniz.", links: [{ href: "/kvkk", label: "KVKK aydınlatma metni" }] },
      { title: "Veri sorumlusu ve başvuru", body: "Veri sorumlusu LEDProje’dir (İstanbul). Kişisel verilerinize ilişkin KVKK madde 11 kapsamındaki taleplerinizi iletişim sayfasındaki kanallardan iletebilirsiniz.", links: [{ href: "/iletisim", label: "İletişim bilgileri" }] },
    ],
    faqs: [
      { question: "Çerezleri reddedersem site çalışır mı?", answer: "Evet. Reddettiğinizde yalnız analitik ölçümleme devre dışı kalır; sayfalar, form ve iletişim kanalları normal biçimde çalışmaya devam eder." },
      { question: "Reklam veya takip çerezi kullanılıyor mu?", answer: "Hayır. Sitede reklam, yeniden pazarlama veya profilleme çerezi bulunmaz. Google Analytics reklam özellikleri kapalıdır." },
    ],
    related: [{ href: "/kvkk", label: "KVKK Aydınlatma Metni" }, { href: "/gizlilik-politikasi", label: "Gizlilik Politikası" }, { href: "/iletisim", label: "İletişim" }],
  },
  // Hukuki metinler: ticari unvan Fc Reklam (kullanıcı onaylı). Vergi no, e-posta/KEP bilinçli
  // olarak boş bırakıldı; başvuru kanalı olarak doğrulanmış telefon/WhatsApp ve adres kullanılır.
  {
    slug: "kvkk", title: "KVKK Aydınlatma Metni", description: "LEDProje'nin 6698 sayılı KVKK kapsamında teklif ve iletişim süreçlerinde işlediği kişisel veriler, amaçları, aktarım ve başvuru hakları.", eyebrow: "Kişisel verilerin korunması", h1: "KVKK Aydınlatma Metni", intro: "Bu metin, 6698 sayılı Kişisel Verilerin Korunması Kanunu’nun 10. maddesi uyarınca, ledproje.com.tr üzerinden teklif talebi veya iletişim kurduğunuzda kişisel verilerinizin nasıl işlendiğini açıklar.", primaryQuery: "ledproje kvkk aydınlatma metni", kind: "corporate", index: true,
    sections: [
      { title: "Veri sorumlusu", body: "Veri sorumlusu, LEDProje markasını işleten Fc Reklam’dır. Adres: Demirciler Sitesi 1. Cd. No:1, Seyitnizam, 34015 Zeytinburnu / İstanbul. Telefon ve WhatsApp: 0501 580 01 01.", links: [{ href: "/iletisim", label: "İletişim bilgileri" }] },
      { title: "İşlenen kişisel veriler", body: "Teklif formunda paylaştığınız veriler işlenir:", bullets: ["Kimlik ve iletişim: ad soyad, telefon numarası.", "Proje bilgisi: şehir, proje/kullanım alanı, kullanım ortamı (iç/dış mekân) ve isteğe bağlı proje notu.", "WhatsApp veya telefonla yazışırken kendi isteğinizle paylaştığınız ek bilgiler (ölçü, saha bilgisi, görsel vb.).", "Site kullanımına ilişkin toplu ölçümleme verileri; yalnız çerez onayı verirseniz toplanır."] },
      { title: "İşleme amaçları", body: "Verileriniz; teklif talebinizi değerlendirmek, sizinle iletişime geçmek, teknik ön değerlendirme ve projelendirme yapmak, teklif sürecini yürütmek, satış sonrası montaj ve teknik servis taleplerini yönetmek ve site kullanılabilirliğini geliştirmek amaçlarıyla işlenir. Verileriniz pazarlama listesi oluşturmak veya satmak için kullanılmaz." },
      { title: "Toplama yöntemi ve hukuki sebep", body: "Veriler, sitedeki teklif formu, WhatsApp, telefon ve iletişim kanalları üzerinden otomatik olmayan ve kısmen otomatik yollarla toplanır. Hukuki sebepler: talebiniz üzerine sözleşme öncesi görüşmenin yürütülmesi (KVKK m. 5/2-c), veri sorumlusunun meşru menfaati (m. 5/2-f) ve teklif formundaki onayınız (m. 5/1). Analitik çerezler yalnız açık rızanızla çalışır.", links: [{ href: "/cerez-politikasi", label: "Çerez Politikası" }] },
      { title: "Teklif formu ve WhatsApp aktarımı", body: "Teklif formunu gönderdiğinizde bilgileriniz sitemizin bir sunucusuna kaydedilmez; formdaki yanıtlarla hazırlanan mesaj, kendi cihazınızdaki WhatsApp üzerinden LEDProje’nin WhatsApp numarasına gönderilmek üzere açılır. Mesajı göndermeniz halinde bu iletişim WhatsApp hizmetinin kendi gizlilik koşullarına da tabidir." },
      { title: "Verilerin aktarılması", body: "Kişisel verileriniz satılmaz. Hizmetin yürütülmesi için gerekli olduğu ölçüde; WhatsApp mesajlaşma hizmeti, çerez onayı vermeniz halinde Google Analytics ölçümleme hizmeti ve yasal yükümlülük doğarsa yetkili kamu kurum ve kuruluşlarıyla paylaşılabilir. Bu hizmet sağlayıcıların sunucuları yurt dışında bulunabileceğinden, aktarım KVKK m. 9 hükümlerine uygun olarak, ölçümleme bakımından açık rızanıza dayanarak yapılır." },
      { title: "Saklama süresi", body: "Teklif ve iletişim verileri, talebinizin sonuçlanması ve ilgili yasal zamanaşımı ve saklama yükümlülükleri sona erene kadar saklanır; süre bitiminde silinir, yok edilir veya anonim hale getirilir. Google Analytics ölçümleme verileri 14 ay sonra otomatik silinir." },
      { title: "KVKK madde 11 kapsamındaki haklarınız", body: "Veri sorumlusuna başvurarak şunları talep edebilirsiniz:", bullets: ["Kişisel verilerinizin işlenip işlenmediğini öğrenme ve bilgi talep etme.", "İşlenme amacını ve amacına uygun kullanılıp kullanılmadığını öğrenme.", "Yurt içinde veya yurt dışında aktarıldığı üçüncü kişileri bilme.", "Eksik veya yanlış işlenmişse düzeltilmesini isteme.", "KVKK m. 7 kapsamında silinmesini veya yok edilmesini isteme ve bunun aktarılan üçüncü kişilere bildirilmesini isteme.", "İşlenen verilerin otomatik sistemlerle analiziyle aleyhinize bir sonuç çıkmasına itiraz etme.", "Kanuna aykırı işlenmesi nedeniyle zarara uğramanız halinde zararın giderilmesini talep etme."] },
      { title: "Başvuru yöntemi", body: "Haklarınıza ilişkin taleplerinizi adınız, iletişim bilginiz ve talebinizin konusuyla birlikte iletişim sayfasındaki kanallardan veya yukarıdaki adrese yazılı olarak iletebilirsiniz. Başvurular, talebin niteliğine göre en geç otuz gün içinde sonuçlandırılır. Başvurunuzun yanıtından memnun kalmazsanız Kişisel Verileri Koruma Kurulu’na şikâyette bulunma hakkınız saklıdır.", links: [{ href: "/iletisim", label: "İletişim" }] },
    ],
    faqs: [
      { question: "Teklif formundaki bilgilerim sitede saklanıyor mu?", answer: "Hayır. Form, bilgilerinizi bir sunucuya kaydetmez; hazırlanan mesaj sizin WhatsApp’ınızda açılır ve siz göndermeden iletilmez." },
      { question: "Verilerimin silinmesini nasıl isteyebilirim?", answer: "İletişim sayfasındaki kanallardan KVKK madde 11 kapsamında talebinizi iletebilirsiniz; yasal saklama yükümlülüğü yoksa verileriniz silinir veya anonim hale getirilir." },
    ],
    related: [{ href: "/gizlilik-politikasi", label: "Gizlilik Politikası" }, { href: "/cerez-politikasi", label: "Çerez Politikası" }, { href: "/iletisim", label: "İletişim" }],
  },
  {
    slug: "gizlilik-politikasi", title: "Gizlilik Politikası", description: "LEDProje web sitesinde hangi bilgilerin toplandığı, nasıl kullanıldığı, üçüncü taraflarla paylaşımı ve verilerinizin güvenliği.", eyebrow: "Kişisel verilerin korunması", h1: "Gizlilik Politikası", intro: "LEDProje (Fc Reklam), ledproje.com.tr ziyaretçilerinin ve teklif talebinde bulunan kişilerin gizliliğine saygı duyar. Bu politika hangi bilgilerin, hangi amaçla ve nasıl kullanıldığını özetler.", primaryQuery: "ledproje gizlilik politikası", kind: "corporate", index: true,
    sections: [
      { title: "Kapsam", body: "Bu politika ledproje.com.tr web sitesi ve bu site üzerinden başlatılan iletişim (teklif formu, WhatsApp, telefon) için geçerlidir. Kişisel verilerin KVKK kapsamındaki ayrıntılı işlenmesi Aydınlatma Metni’nde açıklanmıştır.", links: [{ href: "/kvkk", label: "KVKK Aydınlatma Metni" }] },
      { title: "Hangi bilgileri topluyoruz?", body: "Yalnız sizin paylaştığınız bilgileri ve onay verirseniz toplu ölçümleme verilerini topluyoruz:", bullets: ["Teklif formunda verdiğiniz ad soyad, telefon, şehir, proje/kullanım alanı, kullanım ortamı ve isteğe bağlı proje notu.", "WhatsApp veya telefonla kendi isteğinizle paylaştığınız bilgiler.", "Çerez onayı verirseniz Google Analytics 4 ile sayfa görüntüleme ve etkileşim (teklif formu, WhatsApp yönlendirmesi, alan hesaplama) verileri."] },
      { title: "Bilgileri nasıl kullanıyoruz?", body: "Bilgileriniz taleplerinizi yanıtlamak, teknik ön değerlendirme ve teklif hazırlamak, montaj ve teknik servis süreçlerini yürütmek ile site içeriğini ve kullanılabilirliğini geliştirmek için kullanılır. Bilgileriniz satılmaz, kiralanmaz ve izniniz olmadan reklam amacıyla paylaşılmaz." },
      { title: "Üçüncü taraf hizmetler", body: "Teklif formu bilgileri sunucumuza kaydedilmez; hazırlanan mesaj WhatsApp üzerinden iletilir ve WhatsApp’ın gizlilik koşullarına tabidir. Çerez onayı vermeniz halinde ölçümleme için Google Analytics kullanılır; onay vermediğiniz sürece ölçümleme çerezi yazılmaz. Sitede reklam, yeniden pazarlama veya profilleme amaçlı izleme bulunmaz.", links: [{ href: "/cerez-politikasi", label: "Çerez Politikası" }] },
      { title: "Verilerin güvenliği", body: "Site HTTPS üzerinden sunulur. Telefon, WhatsApp ve yazışma kayıtlarına erişim iş gereği yetkilendirilmiş LEDProje çalışanlarıyla sınırlıdır. İnternet üzerinden hiçbir iletimin tamamen risksiz olmadığını, bu nedenle hassas bilgileri (kimlik, banka veya kart bilgisi) yazışmalarda paylaşmamanızı öneririz." },
      { title: "Saklama ve silme", body: "Bilgileriniz yukarıdaki amaçların gerektirdiği süre ve yasal saklama yükümlülükleri boyunca tutulur, sonrasında silinir veya anonim hale getirilir. Silme talebinizi iletişim kanallarından iletebilirsiniz." },
      { title: "Üçüncü taraf bağlantılar", body: "Sitemiz Google Haritalar ve WhatsApp gibi harici hizmetlere bağlantı verir. Bu hizmetlerin gizlilik uygulamalarından LEDProje sorumlu değildir." },
      { title: "Haklarınız ve iletişim", body: "KVKK madde 11 kapsamındaki haklarınız ve başvuru yöntemi Aydınlatma Metni’nde yer alır. Gizlilikle ilgili soru ve talepleriniz için: Demirciler Sitesi 1. Cd. No:1, Seyitnizam, 34015 Zeytinburnu / İstanbul · 0501 580 01 01.", links: [{ href: "/iletisim", label: "İletişim bilgileri" }] },
      { title: "Politikadaki değişiklikler", body: "Bu politika mevzuat veya site işleyişindeki değişikliklere göre güncellenebilir; güncel sürüm her zaman bu sayfada yayımlanır." },
    ],
    faqs: [
      { question: "Bilgilerim üçüncü kişilere satılıyor mu?", answer: "Hayır. Kişisel verileriniz satılmaz, kiralanmaz ve pazarlama amacıyla üçüncü kişilerle paylaşılmaz." },
      { question: "Çerezleri reddedersem teklif alabilir miyim?", answer: "Evet. Çerezleri reddetmeniz yalnız analitik ölçümlemeyi devre dışı bırakır; teklif formu, WhatsApp ve telefon kanalları normal çalışır." },
    ],
    related: [{ href: "/kvkk", label: "KVKK Aydınlatma Metni" }, { href: "/cerez-politikasi", label: "Çerez Politikası" }, { href: "/iletisim", label: "İletişim" }],
  },
];

export const allPages: SeoPage[] = [...pages, ...servicePages, ...corporatePages, ...pitchPages, ...cityPages];
export const pageMap = new Map(allPages.map((page) => [page.slug, page]));
