import type { SeoPage } from "@/lib/types";
import { indoorCommon, indoorPitchRows, outdoorCommon, outdoorPitchRows } from "@/lib/technical-data";
import { cityPages } from "@/lib/cities";
import { pitchPages } from "@/lib/pitch-pages";

const quote = { href: "/iletisim#teklif", label: "Projenize özel teklif alın" };
const prices = { href: "/led-ekran-fiyatlari", label: "Fiyatlandırma yaklaşımı" };
const mounting = { href: "/led-ekran-montaji", label: "Montaj ve devreye alma" };
const commonFaq = [
  { question: "LED ekran için sabit fiyat verilebilir mi?", answer: "Hayır. Ölçü, piksel aralığı, kullanım ortamı, kabinet, kontrol sistemi, konstrüksiyon ve montaj koşulları birlikte değerlendirilir." },
  { question: "Türkiye geneline hizmet veriyor musunuz?", answer: "Evet. LEDProje, Türkiye genelindeki satış ve proje ihtiyaçları için teknik değerlendirme, montaj ve servis planlaması yapar." },
];

const pages: SeoPage[] = [
  {
    slug: "led-ekranlar", title: "LED Ekran Sistemleri", description: "İç ve dış mekân LED ekran sistemlerini, poster, esnek ve totem çözümlerini proje gereksiniminize göre karşılaştırın.", eyebrow: "Ürün ve sistem merkezi", h1: "Profesyonel LED Ekran Sistemleri", intro: "LED ekran yalnızca panellerden oluşmaz. Görüntü yüzeyi; kabinet, güç, veri, kontrol, mekanik taşıyıcı ve doğru yapılandırmayla birlikte çalışan bir sistemdir.", primaryQuery: "led ekran sistemleri", kind: "hub", index: true,
    sections: [
      { title: "Kullanım ortamına göre doğru sistem", body: "İç mekânda yakın izleme ve görüntü bütünlüğü; dış mekânda parlaklık, çevresel dayanım ve erişim koşulları öne çıkar. Poster, esnek ve totem sistemleri ise farklı fiziksel yerleşim ihtiyaçlarını karşılar.", links: [{ href: "/ic-mekan-led-ekran", label: "İç mekân sistemleri" }, { href: "/dis-mekan-led-ekran", label: "Dış mekân sistemleri" }] },
      { title: "Panelden devreye almaya sistem bütünlüğü", body: "Uygun LED panel/modül seçimi; projeye özel kabinet, güç kaynakları, enerji dağıtımı, alıcı kart, kontrol altyapısı, veri kablolaması ve mekanik uygulamayla tamamlanır. LEDProje bu bileşenleri proje hedefi etrafında entegre eder." },
      { title: "LED ekran paneli hangi anlama gelir?", body: "“LED ekran panel” ve “LED panel ekran” ifadeleri çoğu zaman ekran yüzeyini veya kabinet birimini tarif eder. Proje kararında tek bir panel yerine toplam sistem ölçüsü, çözünürlük, izleme mesafesi ve işletme koşulları değerlendirilmelidir." },
    ], faqs: commonFaq, related: [{ href: "/poster-led-ekran", label: "Poster LED ekran" }, { href: "/esnek-led-ekran", label: "Esnek LED ekran" }, { href: "/totem-led-ekran", label: "Totem LED ekran" }, quote],
  },
  {
    slug: "ic-mekan-led-ekran", title: "İç Mekân LED Ekran Sistemleri", description: "Mağaza, showroom, toplantı salonu ve kurumsal alanlar için yakın izlemeye uygun iç mekân LED ekran çözümleri.", eyebrow: "Yakın izleme · kontrollü ışık", h1: "İç Mekân LED Ekran Sistemleri", intro: "İç mekân projelerinde piksel aralığı, izleme mesafesi ve içerik türü birlikte ele alınır. Amaç yalnız parlak bir yüzey değil, doğru mesafeden bütünlüklü ve okunaklı görüntüdür.", primaryQuery: "iç mekan led ekran", kind: "product", index: true, specs: indoorPitchRows,
    sections: [
      { title: "Yakın izleme için piksel aralığı seçimi", body: "P1.53 ve P1.86 gibi daha sık piksel yapıları yakın izleme gereken alanlara; P2.5, P3 ve P4 seçenekleri ise mesafe ve ekran ölçeğine göre farklı projelere yönelir. Nihai seçim, saha ölçüsü ve içerik hedefiyle doğrulanır.", bullets: indoorCommon },
      { title: "İç mekân LED ekran fiyatları", body: "Fiyat; yalnız m² üzerinden oluşmaz. Toplam çözünürlük, pitch, kabinet yapısı, kontrol sistemi, taşıyıcı uygulama, enerji/data hattı ve montaj koşulları proje bedelini birlikte belirler.", links: [prices, { href: "/led-ekran-metrekare-fiyati", label: "Alan hesaplama aracı" }] },
      { title: "Mağazadan toplantı salonuna", body: "Vitrin arkası, showroom, lobi, konferans ve kurumsal sunum alanlarında içerik okunurluğu ve bakım erişimi farklılaşır. Projelendirme bu kullanım akışına göre yapılır." },
    ], faqs: [{ question: "İç mekân LED ekranda en iyi pitch hangisidir?", answer: "Tek bir doğru pitch yoktur. En yakın izleme mesafesi, ekran ölçüsü, içerik çözünürlüğü ve bütçe birlikte değerlendirilmelidir." }, ...commonFaq], related: [{ href: "/p2-5-led-ekran", label: "P2.5 LED ekran" }, { href: "/magaza-led-ekran", label: "Mağaza çözümleri" }, mounting, quote],
  },
  {
    slug: "dis-mekan-led-ekran", title: "Dış Mekân LED Ekran Sistemleri", description: "Yüksek parlaklık, çevresel koruma ve saha koşullarına göre projelendirilen profesyonel dış mekân LED ekran sistemleri.", eyebrow: "Yüksek parlaklık · saha dayanımı", h1: "Dış Mekân LED Ekran Sistemleri", intro: "Dış mekân LED ekran projelerinde görünürlük kadar kabinet, koruma sınıfı, taşıyıcı sistem, enerji dağıtımı ve servis erişimi de sistem kararının parçasıdır.", primaryQuery: "dış mekan led ekran", kind: "product", index: true, specs: outdoorPitchRows,
    sections: [
      { title: "Gün ışığında görünürlük ve koruma", body: "Kaynak teknik verilere göre dış mekân ailesi yaklaşık 5.500–6.500 nit parlaklık, ön IP65 ve arka IP54 koruma sunar. Gerçek proje seçimi cephe yönü, izleme mesafesi ve erişim koşullarıyla doğrulanır.", bullets: outdoorCommon },
      { title: "Dış mekân LED ekran fiyatları", body: "Pixel pitch ve toplam alanın yanı sıra kabinet, çelik konstrüksiyon, erişim ekipmanı, enerji/data altyapısı, lokasyon ve montaj planı fiyat üzerinde belirleyicidir. Bu nedenle sabit ürün veya m² fiyatı gösterilmez.", links: [prices] },
      { title: "Ürün kategorisi ile cephe uygulaması arasındaki fark", body: "Bu sayfa dış mekân ürün ailesini ve teknik seçim kriterlerini açıklar. Bina cephesine özel konstrüksiyon, erişim ve mimari entegrasyon için dış cephe çözüm sayfası kullanılmalıdır.", links: [{ href: "/dis-cephe-led-ekran", label: "Dış cephe LED ekran projeleri" }] },
    ], faqs: [{ question: "Outdoor LED ekran hangi pitch seçeneklerinde sunulur?", answer: "Kaynak teknik kapsam P2.5, P3, P4, P5 ve P10 seçeneklerini içerir. Uygun pitch izleme mesafesine ve uygulama ölçeğine göre belirlenir." }, ...commonFaq], related: [{ href: "/p5-led-ekran", label: "P5 LED ekran" }, { href: "/p10-led-ekran", label: "P10 LED ekran" }, mounting, quote],
  },
  {
    slug: "poster-led-ekran", title: "Poster LED Ekran Sistemleri", description: "Mağaza, showroom ve karşılama alanları için P1.86, P2.5 ve P3 poster LED ekran sistemleri.", eyebrow: "Dikey dijital iletişim", h1: "Poster LED Ekran Sistemleri", intro: "Poster LED ekran; dikey içerik akışı gereken mağaza, showroom ve karşılama noktalarında hareketli kampanya ve ürün iletişimi için planlanır.", primaryQuery: "poster led ekran", kind: "product", index: true,
    sections: [{ title: "Dikey format için doğru içerik yüzeyi", body: "Poster sistemlerinde ekran konumu, yaklaşma mesafesi ve içerik oranı birlikte planlanır. Kaynak teknik kapsam P1.86, P2.5 ve P3 seçeneklerini içerir." }, { title: "Tekli veya çoklu yerleşim", body: "Birden fazla poster ekranın kullanıldığı projelerde içerik senkronizasyonu, elektrik/data dağıtımı ve mekândaki yaya akışı değerlendirilir." }, { title: "Proje fiyatını belirleyenler", body: "Pitch, adet, kontrol senaryosu, taşıyıcı biçimi, montaj ve içerik yönetimi gereksinimi teklif kapsamını oluşturur.", links: [prices] }], faqs: [{ question: "Poster LED ekran nerede kullanılır?", answer: "Mağaza girişi, vitrin yakını, showroom, fuaye ve kurumsal karşılama gibi dikey içerik gereken alanlarda değerlendirilebilir." }, ...commonFaq], related: [{ href: "/magaza-led-ekran", label: "Mağaza LED ekran" }, { href: "/led-ekran-kontrol-sistemleri", label: "Kontrol sistemleri" }, quote],
  },
  {
    slug: "esnek-led-ekran", title: "Esnek LED Ekran Sistemleri", description: "Kavisli ve özel yüzeyler için P1.86 ve P2.5 esnek LED ekran çözümleri; projelendirme, montaj ve devreye alma.", eyebrow: "Kavisli yüzey · özel geometri", h1: "Esnek LED Ekran Sistemleri", intro: "Esnek LED ekran sistemleri, düz bir kabinet diziliminin karşılayamadığı kavisli veya özel geometrili iç mekân yüzeyleri için değerlendirilir.", primaryQuery: "esnek led ekran", kind: "product", index: true,
    sections: [{ title: "Yüzeye göre mekanik tasarım", body: "Esnek modül tek başına proje değildir. Yarıçap, taşıyıcı yüzey, modül yerleşimi, kablo rotası ve bakım erişimi birlikte çözümlenir." }, { title: "Doğrulanmış pitch kapsamı", body: "Kaynak dokümanda esnek ürün ailesi için P1.86 ve P2.5 seçenekleri yer alır. Proje sınırları uygulama geometrisi üzerinden doğrulanır." }, { title: "İçerik ve görüntü sürekliliği", body: "Kavis boyunca görüntünün bozulmaması için içerik tasarım alanı, kontrol sistemi ve fiziksel modül hizalaması koordineli yürütülür." }], faqs: [{ question: "Esnek LED ekran her eğri yüzeye uygulanabilir mi?", answer: "Hayır. Uygulanabilir yarıçap ve mekanik sınırlar ürün ve proje detaylarıyla doğrulanmalıdır; doğrulanmadan teknik değer taahhüt edilmez." }, ...commonFaq], related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân LED ekran" }, { href: "/p2-5-led-ekran", label: "P2.5 LED ekran" }, quote],
  },
  {
    slug: "totem-led-ekran", title: "Totem LED Ekran Sistemleri", description: "P3, P4 ve P5 totem LED ekranlar için saha, taşıyıcı, kontrol ve montaj odaklı anahtar teslim proje yaklaşımı.", eyebrow: "Dikey dış mekân görünürlüğü", h1: "Totem LED Ekran Sistemleri", intro: "Totem LED ekran; ekran yüzeyi, dış gövde, taşıyıcı temel, enerji/data erişimi ve bakım senaryosunun tek sistem olarak ele alındığı bir dış mekân uygulamasıdır.", primaryQuery: "totem led ekran", kind: "product", index: true,
    sections: [{ title: "P3, P4 ve P5 seçenekleri", body: "Kaynak kapsamındaki pitch alternatifleri, izleme mesafesi ve totemin sahadaki konumuna göre değerlendirilir. Daha sık pitch her proje için otomatik olarak daha doğru değildir." }, { title: "Gövde ve taşıyıcı sistem", body: "Rüzgâr ve statik hesaplar yetkili proje disiplinlerinin doğrulamasını gerektirir. LEDProje ekran entegrasyonu, kabinet, enerji/data ve montaj koordinasyonunu proje kapsamına göre yönetir." }, { title: "İçerik kontrolü ve servis erişimi", body: "Senkron veya asenkron yayın ihtiyacı, bağlantı altyapısı ve bakım erişimi saha keşfinde belirlenir." }], faqs: [{ question: "Totem LED ekran için temel gerekir mi?", answer: "Saha ve taşıyıcı çözümüne göre gerekebilir. Statik ve uygulama detayları proje bazında yetkili disiplinlerce doğrulanmalıdır." }, ...commonFaq], related: [{ href: "/dis-mekan-led-ekran", label: "Dış mekân LED ekran" }, { href: "/p4-led-ekran", label: "P4 LED ekran" }, quote],
  },
  {
    slug: "led-ekran-kontrol-sistemleri", title: "LED Ekran Kontrol Sistemleri", description: "Sender, receiver, controller, senkron ve asenkron yayın yapıları için projeye uygun LED ekran kontrol sistemi entegrasyonu.", eyebrow: "Görüntü ve data yönetimi", h1: "LED Ekran Kontrol Sistemleri", intro: "Kontrol sistemi; kaynaktaki görüntünün ekran yüzeyine doğru çözünürlük, tarama ve zamanlama ile aktarılmasını sağlar. Seçim ekran çözünürlüğüne ve yayın senaryosuna göre yapılır.", primaryQuery: "led ekran kontrol sistemleri", kind: "technical", index: true,
    sections: [{ title: "Sender, receiver ve controller yapısı", body: "Sender/controller görüntü kaynağını işler; receiver kartlar kabinet ve modül dağılımına göre veriyi ekrana taşır. Kart sayısı ve bağlantı topolojisi proje çözünürlüğüyle hesaplanır." }, { title: "Senkron ve asenkron yayın", body: "Canlı HDMI kaynağı gereken projelerde senkron; planlı içerik oynatma gereken uygun projelerde asenkron yapı değerlendirilebilir. Uzaktan yönetim ancak bağlantı ve güvenlik gereksinimleri doğrulandığında planlanır." }, { title: "Konfigürasyon ve devreye alma", body: "Data hattı, mapping, ekran çözünürlüğü, parlaklık ve görüntü ayarları montaj sonrası test edilerek devreye alınır." }], faqs: [{ question: "Kontrol sistemi ekrandan ayrı seçilebilir mi?", answer: "Kontrol kapasitesi toplam piksel yükü, giriş kaynakları ve yayın biçimiyle uyumlu olmalıdır; bağımsız bir aksesuar gibi seçilmemelidir." }, ...commonFaq], related: [{ href: "/led-ekranlar", label: "LED ekran sistemleri" }, mounting, quote],
  },
  {
    slug: "led-ekran-fiyatlari", title: "LED Ekran Fiyatları Nasıl Belirlenir?", description: "LED ekran fiyatlarını belirleyen ölçü, pixel pitch, kabinet, kontrol, konstrüksiyon ve montaj unsurlarını öğrenin; proje teklifi alın.", eyebrow: "Proje maliyeti rehberi", h1: "LED Ekran Fiyatları Nasıl Belirlenir?", intro: "Profesyonel LED ekran fiyatı sabit bir ürün etiketinden değil, ekran yüzeyiyle birlikte çalışan teknik ve mekanik sistemin toplamından oluşur. Bu sayfada rakam vermeden teklif kapsamını şeffaflaştırıyoruz.", primaryQuery: "led ekran fiyatları", kind: "solution", index: true,
    sections: [
      { title: "Ekran ölçüsünün fiyata etkisi", body: "En ve boy toplam modül/kabinet adedini, çözünürlüğü, güç ihtiyacını ve taşıyıcı sistemi etkiler. Ölçü yalnız alanı değil, sistem geometrisini de belirler." },
      { title: "Piksel aralığı maliyeti nasıl değiştirir?", body: "Daha sık piksel aralığı aynı alanda daha fazla piksel ve farklı kontrol kapasitesi anlamına gelir. Doğru karar en yakın izleme mesafesi ve içerik hedefiyle verilir." },
      { title: "İç ve dış mekân maliyet farkları", body: "Dış mekân görünürlüğü, çevresel koruma, kabinet, konstrüksiyon ve erişim koşulları; iç mekânda ise yakın izleme ve mimari entegrasyon farklı maliyet bileşenleri oluşturur." },
      { title: "Kabinet, konstrüksiyon ve erişim", body: "Projeye özel kabinet/kasa, taşıyıcı sistem, cephe erişimi ve montaj ekipmanı teklif kapsamına göre hesaplanır. Statik gereklilikler ilgili uzmanlıklarla doğrulanır." },
      { title: "Kontrol, enerji ve veri altyapısı", body: "Kontrol sistemi kapasitesi, alıcı kart dağılımı, güç kaynakları, enerji panosu ve kablolama sistemin büyüklüğüne ve kullanım senaryosuna göre boyutlandırılır." },
      { title: "Montaj, devreye alma ve teknik servis", body: "Lokasyon, lojistik, saha çalışma koşulları, modül hizalama, görüntü ayarı, test ve servis kapsamı toplam proje fiyatına dahildir." },
      { title: "Projenize özel fiyat nasıl hesaplanır?", body: "En, boy, şehir, iç/dış mekân ve kullanım alanını paylaşın. Teknik ekip izleme mesafesi ile saha koşullarını netleştirerek uygun sistem kapsamını çıkarır.", links: [{ href: "/iletisim#teklif", label: "Teklif bilgilerini gönderin" }, { href: "/led-ekran-metrekare-fiyati", label: "Ekran alanını hesaplayın" }] },
    ], faqs: [{ question: "Neden web sitesinde TL veya m² fiyatı yok?", answer: "Aynı alandaki iki ekran; pitch, ortam, kabinet, kontrol, konstrüksiyon ve montaj açısından farklı sistemler olabilir. Doğrulanmamış bir rakam yanıltıcı olacağı için fiyat proje verileriyle hesaplanır." }, ...commonFaq], related: [{ href: "/led-ekran-metrekare-fiyati", label: "Metrekare fiyatı ve alan hesabı" }, { href: "/ic-mekan-led-ekran", label: "İç mekân fiyat faktörleri" }, { href: "/dis-mekan-led-ekran", label: "Dış mekân fiyat faktörleri" }, quote],
  },
  {
    slug: "led-ekran-metrekare-fiyati", title: "LED Ekran Metrekare Fiyatı ve Alan Hesabı", description: "LED ekran alanınızı en ve boy ölçüsüyle hesaplayın; m² fiyatının neden tek başına proje bedelini belirlemediğini öğrenin.", eyebrow: "Alan hesabı · teklif başlangıcı", h1: "LED Ekran Metrekare Fiyatı Nasıl Hesaplanır?", intro: "Ekran alanı en × boy formülüyle hesaplanır. Fakat m² yalnız fiziksel büyüklüğü gösterir; net fiyat için pitch, ortam, kabinet, kontrol, konstrüksiyon ve montaj bilgileri gerekir.", primaryQuery: "led ekran metrekare fiyatı", kind: "solution", index: true,
    sections: [{ title: "Aynı m², neden farklı proje?", body: "P2.5 ve P5 ekran aynı fiziksel alana sahip olsa bile toplam piksel sayısı, ideal izleme mesafesi ve kontrol yükü aynı değildir. İç/dış mekân koruması ve parlaklık gereksinimi de sistem kapsamını değiştirir." }, { title: "m² hesabına eklenen proje bileşenleri", body: "Kabinet geometrisi, taşıyıcı konstrüksiyon, controller/receiver yapısı, güç ve data dağıtımı, saha erişimi, lojistik, montaj ve devreye alma net teklifte değerlendirilir." }, { title: "Genel fiyat rehberinden farkı", body: "Bu sayfa alan ve m² hesaplama beklentisini karşılar. Toplam proje maliyetini etkileyen tüm kalemlerin ayrıntılı açıklaması ayrı fiyat rehberindedir.", links: [prices] }], faqs: [{ question: "LED ekran alanı nasıl hesaplanır?", answer: "Metre cinsinden en ile boy çarpılır. Örneğin 6 m × 3 m ekran alanı 18 m²’dir; bu sonuç fiyat değildir." }, ...commonFaq], related: [prices, { href: "/p2-5-led-ekran", label: "P2.5 ve piksel yoğunluğu" }, { href: "/p5-led-ekran", label: "P5 ve izleme mesafesi" }, quote],
  },
  {
    slug: "magaza-led-ekran", title: "Mağaza LED Ekran Çözümleri", description: "Vitrin, iç alan ve kampanya iletişimi için mağazaya özel LED ekran projelendirme, montaj ve içerik altyapısı.", eyebrow: "Perakende görünürlüğü", h1: "Mağaza LED Ekran Çözümleri", intro: "Mağaza LED ekranı, ürün kategorisinden çok müşteri akışı ve iletişim hedefiyle şekillenen bir kullanım senaryosudur. Vitrin, giriş ve iç alan için farklı çözüm gerekir.", primaryQuery: "mağaza led ekran", kind: "solution", index: true,
    sections: [{ title: "Vitrin ve iç alanı ayrı değerlendirin", body: "Vitrin arkasında gün ışığı, cam yansıması ve dışarıdan izleme; iç alanda ise yakın mesafe, içerik detayı ve mimari uyum önem kazanır." }, { title: "Pitch ve yerleşim", body: "Yakın izlenen ürün iletişiminde daha sık pitch seçenekleri değerlendirilir. Ekran yüksekliği ve bakış açısı, içerik okunurluğu için ölçüyle birlikte planlanır." }, { title: "Kampanya yönetimi ve kontrol", body: "Tek mağaza veya birden fazla ekran için içerik kaynağı, yayın sıklığı ve uzaktan yönetim gereksinimi proje aşamasında tanımlanır." }], faqs: [{ question: "Mağaza vitrini için iç mekân ekran kullanılabilir mi?", answer: "Konum, doğrudan ışık, cam yansıması ve çevresel koşullar görülmeden karar verilmemelidir. Teknik ön değerlendirme uygun parlaklık ve ürün ailesini belirler." }, ...commonFaq], related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân ürün kategorisi" }, { href: "/poster-led-ekran", label: "Poster LED ekran" }, prices, quote],
  },
  {
    slug: "dis-cephe-led-ekran", title: "Dış Cephe LED Ekran Projeleri", description: "Bina cepheleri için LED ekran; konstrüksiyon, erişim, enerji, data, montaj ve devreye alma odaklı proje çözümü.", eyebrow: "Mimari ve mekanik entegrasyon", h1: "Dış Cephe LED Ekran Projeleri", intro: "Dış cephe LED ekran, bir ürün seçiminin ötesinde bina yüzeyi, taşıyıcı konstrüksiyon, erişim, enerji/data ve servis planının birlikte çözüldüğü uygulama projesidir.", primaryQuery: "dış cephe led ekran", kind: "solution", index: true,
    sections: [{ title: "Cepheye özel saha değerlendirmesi", body: "Cephe yönü, ekran kotu, izleme aksı, montaj erişimi ve bakım yaklaşımı ölçülmeden sistem kesinleştirilmez." }, { title: "Konstrüksiyon ve entegrasyon", body: "Ekran kabinetleri ile bina arasındaki mekanik arayüz projeye özel çözülür. Gerekli statik ve yapısal doğrulamalar ilgili yetkin disiplinlerin kapsamındadır." }, { title: "Dış mekân ürün kategorisinden farkı", body: "Dış mekân sayfası parlaklık, IP ve pitch gibi ürün kriterlerini açıklar. Bu sayfa ise bina cephesi uygulamasının saha, mekanik ve operasyon kapsamına odaklanır.", links: [{ href: "/dis-mekan-led-ekran", label: "Dış mekân ürün kriterleri" }] }], faqs: [{ question: "Cephe LED ekranında keşif neden gereklidir?", answer: "Ölçü, kot, görüş açısı, güç/data rotası, taşıyıcı yüzey ve erişim koşulları proje kapsamını doğrudan etkiler." }, ...commonFaq], related: [{ href: "/dis-mekan-led-ekran", label: "Dış mekân LED ekran" }, mounting, { href: "/led-ekran-kesif-projelendirme", label: "Keşif ve projelendirme" }, quote],
  },
  {
    slug: "avm-led-ekran", title: "AVM LED Ekran Çözümleri", description: "AVM girişleri, ortak alanlar, yönlendirme ve kampanya iletişimi için profesyonel LED ekran sistem entegrasyonu.", eyebrow: "Ortak alan iletişimi", h1: "AVM LED Ekran Çözümleri", intro: "AVM projelerinde ekran; ziyaretçi akışı, izleme mesafesi, mimari yüzey, çalışma saatleri ve içerik yönetimiyle birlikte planlanır.", primaryQuery: "avm led ekran", kind: "solution", index: true,
    sections: [{ title: "Giriş, atrium ve ortak alan", body: "Her noktanın görüş açısı ve yaklaşma mesafesi farklıdır. Büyük yüzey, dikey poster veya kavisli ekran seçimi yerleşime göre yapılır." }, { title: "Operasyonla uyumlu montaj", body: "Saha erişimi, çalışma zamanları, enerji/data hattı ve güvenli montaj planı AVM yönetimiyle koordinasyon gerektirebilir." }, { title: "İçerik kontrolü", body: "Canlı kaynak, planlı kampanya veya çoklu ekran senaryosu; uygun kontrol sistemi ve data topolojisiyle hazırlanır." }], faqs: [{ question: "AVM için tek bir LED ekran tipi var mı?", answer: "Hayır. İç/dış konum, izleme mesafesi, ekran biçimi ve içerik akışı farklı ürün ve kontrol yapılarına yöneltebilir." }, ...commonFaq], related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân LED ekran" }, { href: "/esnek-led-ekran", label: "Esnek LED ekran" }, mounting, quote],
  },
];

const servicePages: SeoPage[] = [
  ["led-ekran-kesif-projelendirme", "LED Ekran Keşif ve Projelendirme", "led ekran keşif ve projelendirme", "Doğru sistem; ölçü, izleme mesafesi, ortam ve operasyon ihtiyacı netleştirilerek başlar.", ["İhtiyaç ve kullanım senaryosu", "Ölçü, izleme aksı ve saha koşulları", "Pitch, kabinet, kontrol ve taşıyıcı kapsamı"]],
  ["led-ekran-montaji", "LED Ekran Montajı ve Devreye Alma", "led ekran montajı", "LEDProje’nin kendi teknik ekibi, mekanik montajdan görüntü ayarı ve teste kadar devreye alma sürecini yürütür.", ["Taşıyıcı ve kabinet montajı", "Güç ve data kablolaması", "Modül hizalama, konfigürasyon ve test"]],
  ["led-ekran-bakim-onarim", "LED Ekran Bakım ve Onarım", "led ekran bakım onarım", "Planlı bakım ve arıza değerlendirmesi; sistem yapısı, erişim koşulları ve değişmesi gereken bileşenlere göre ele alınır.", ["Görsel ve fiziksel kontrol", "Güç, data ve modül değerlendirmesi", "Müdahale kapsamının proje bazında planlanması"]],
  ["led-ekran-teknik-servis", "LED Ekran Teknik Servis", "led ekran teknik servis", "Satış sonrası teknik servis LEDProje tarafından sağlanır; servis kapsamı sistem ve saha verileriyle belirlenir.", ["Arıza bilgisinin alınması", "Uzaktan ön değerlendirme", "Gerektiğinde planlı saha müdahalesi"]],
].map(([slug, h1, primaryQuery, intro, bullets]) => ({ slug, title: h1, description: `${h1} için LEDProje teknik yaklaşımı, süreç kapsamı ve proje bazlı destek.`, eyebrow: "Profesyonel hizmet", h1, intro, primaryQuery, kind: "service", index: true, sections: [{ title: "Süreç nasıl ilerler?", body: "Teknik kapsam, mevcut sistem bilgisi ve saha koşulları alınarak netleştirilir. Doğrulanmayan süre veya sonuç taahhüdü verilmez.", bullets }, { title: "Sistem bütünlüğü", body: "Panel/modül, kabinet, güç, receiver/data, kontrol ve mekanik bileşenler birbirinden bağımsız değil, çalışan sistem bütünü içinde değerlendirilir." }, { title: "Teklif ve planlama", body: "Şehir, ölçü, kullanım ortamı ve mevcut altyapı bilgileriyle teknik ön değerlendirme başlatılır.", links: [quote] }], faqs: commonFaq, related: [{ href: "/led-ekranlar", label: "LED ekran sistemleri" }, prices, quote] })) as SeoPage[];

const corporatePages: SeoPage[] = [
  { slug: "teknik-bilgi", title: "LED Ekran Teknik Bilgi Merkezi", description: "Pixel pitch, izleme mesafesi, parlaklık, IP koruma ve kontrol sistemleri için teknik başlangıç rehberi.", eyebrow: "Karar destek merkezi", h1: "LED Ekran Teknik Bilgi", intro: "Proje kararını etkileyen kavramları satış diliyle değil, kullanım sonucuyla ilişkilendirerek açıklıyoruz.", primaryQuery: "led ekran teknik bilgi", kind: "hub", index: true, sections: [{ title: "Pixel pitch ve izleme mesafesi", body: "Pitch, komşu piksellerin merkezleri arasındaki milimetre mesafesidir. Daha düşük değer daha sık piksel demektir; seçim en yakın izleme mesafesine göre yapılır.", links: [{ href: "/p2-5-led-ekran", label: "P2.5 rehberi" }, { href: "/p4-led-ekran", label: "P4 rehberi" }, { href: "/p5-led-ekran", label: "P5 rehberi" }, { href: "/p10-led-ekran", label: "P10 rehberi" }] }, { title: "Nit, IP ve çalışma ortamı", body: "Parlaklık çevresel ışıkla; IP koruma ise ekipmanın toz ve suya karşı koruma seviyesiyle ilgilidir. İç ve dış mekân ürünleri bu yüzden aynı kapsamda değerlendirilmez." }, { title: "Kontrol sistemi nasıl çalışır?", body: "Görüntü kaynağı controller/sender üzerinden receiver kartlara, oradan kabinet ve modüllere dağıtılır.", links: [{ href: "/led-ekran-kontrol-sistemleri", label: "Kontrol sistemi detayları" }] }], faqs: commonFaq, related: [{ href: "/ic-mekan-led-ekran", label: "İç mekân teknik verileri" }, { href: "/dis-mekan-led-ekran", label: "Dış mekân teknik verileri" }, quote] },
  { slug: "hakkimizda", title: "Hakkımızda", description: "LEDProje’nin profesyonel LED ekran sistem entegrasyonu, montaj ve teknik servis yaklaşımı.", eyebrow: "LEDProje", h1: "Tek Ekran Değil, Çalışan Bir Sistem Kuruyoruz", intro: "LEDProje, profesyonel LED ekran sistemlerinin projelendirme, sistem entegrasyonu, montaj, devreye alma ve satış sonrası teknik servis süreçlerini tek noktadan yöneten İstanbul merkezli bir teknoloji ve proje firmasıdır.", primaryQuery: "LEDProje", kind: "corporate", index: true, sections: [{ title: "Sistem entegratörü ve proje firması", body: "Uygun panel/modül tedarikinden projeye özel kabinet, güç, veri, kontrol ve mekanik uygulamaya kadar bileşenleri tek proje hedefi etrafında birleştiririz." }, { title: "Kendi teknik ekibimizle saha uygulaması", body: "Montaj, modül hizalama, sistem yapılandırması, görüntü ayarı, test ve devreye alma LEDProje teknik ekibi tarafından yürütülür." }, { title: "İstanbul’dan Türkiye geneline", body: "Türkiye genelindeki projelere satış, montaj ve teknik servis hizmeti planlarız; başka şehirlerde fiziksel şube iddiasında bulunmayız." }], faqs: commonFaq, related: [{ href: "/led-ekran-kesif-projelendirme", label: "Proje yaklaşımımız" }, mounting, quote] },
  { slug: "projeler", title: "LED Ekran Projeleri", description: "LEDProje proje arşivi gerçek saha verileri ve onaylı görseller tamamlandığında yayınlanacaktır.", eyebrow: "Proje arşivi hazırlanıyor", h1: "LED Ekran Projeleri", intro: "Gerçek proje detayları ve kullanım izinleri doğrulanmadan örnek müşteri, görsel veya performans verisi yayınlamıyoruz.", primaryQuery: "led ekran projeleri", kind: "corporate", index: false, sections: [{ title: "Doğrulanmış proje modeli", body: "Yayınlanacak her çalışma; proje adı, şehir, sektör, ortam, ölçü, pitch, kullanılan sistem, montaj kapsamı ve onaylı görsellerle belgelenir." }, { title: "Bu sırada projenizi değerlendirebiliriz", body: "Benzer uygulama iddiası üretmeden, kendi sahanızın ölçü ve kullanım koşullarını teknik ekip ile paylaşabilirsiniz.", links: [quote] }], faqs: [], related: [{ href: "/led-ekranlar", label: "Sistemleri inceleyin" }, quote] },
  ...[
    ["kvkk", "KVKK Aydınlatma Metni"], ["gizlilik-politikasi", "Gizlilik Politikası"], ["cerez-politikasi", "Çerez Politikası"],
  ].map(([slug, h1]) => ({ slug, title: h1, description: `${h1} yayına alınmadan önce hukuki onay beklemektedir.`, eyebrow: "Hukuki metin · taslak durumu", h1, intro: "Bu metnin kapsamı ve veri sorumlusu bilgileri yetkili hukuk incelemesiyle doğrulanmadan indexlenmeyecektir.", primaryQuery: h1, kind: "corporate" as const, index: false, sections: [{ title: "Yayın öncesi doğrulama", body: "İletişim formu, WhatsApp yönlendirmesi, ölçümleme tercihleri ve saklama süreçleri kesinleştirildikten sonra gerçek politika metni hazırlanmalıdır." }], faqs: [], related: [{ href: "/iletisim", label: "İletişim" }] })),
];

export const allPages: SeoPage[] = [...pages, ...servicePages, ...corporatePages, ...pitchPages, ...cityPages];
export const pageMap = new Map(allPages.map((page) => [page.slug, page]));
