export const projectSectorGroups = [
  { label: "Perakende ve ticari işletmeler", sectors: ["AVM", "Mağaza", "Market", "Kuyumcu", "Eczane", "Pastane ve fırın", "Restoran ve kafe", "Showroom", "Otomotiv galerisi"] },
  { label: "Kurumsal ve eğitim alanları", sectors: ["İşyeri ve ofis", "Kurumsal lobi", "Okul ve eğitim kurumu", "Toplantı ve konferans salonu", "Kontrol merkezi", "Fabrika ve üretim tesisi", "Belediye ve kamu alanı", "Hastane ve klinik"] },
  { label: "Konaklama ve etkinlik", sectors: ["Otel", "Düğün ve davet salonu", "Sahne ve organizasyon", "Fuar ve kongre", "Spor salonu ve arena", "Etkinlik alanı"] },
  { label: "Mimari ve dış mekân", sectors: ["Bina cephesi", "Açık alan ve meydan", "Totem ve giriş alanı", "Yol ve yönlendirme ekranı", "Dış mekân reklam ekranı"] },
] as const;
export type ProjectSector = (typeof projectSectorGroups)[number]["sectors"][number];
export type ProjectStatus = "draft" | "placeholder" | "published" | "archived";
export type ProjectEnvironment = "İç mekân" | "Dış mekân";
export type ProjectPermission = "granted" | "pending" | "denied";
export type ProjectImage = { src: string; alt: string; kind: "cover" | "desktop-cover" | "mobile-cover" | "before" | "installation" | "completed" | "detail" | "video-poster"; order: number };
export type ProjectVideo = { title: string; type: "local" | "youtube" | "vimeo"; url: string; posterImage: string; posterAlt: string; description?: string; publicationPermission: ProjectPermission; order: number };
export type ProjectReference = { id: string; brandName: string; logo?: string; darkLogo?: string; logoAlt: string; projectSlug: string; sector: ProjectSector; publicationPermission: ProjectPermission; status: ProjectStatus; order: number; isPlaceholder: boolean };
export type SectorProject = {
  id: string; slug: string; title: string; shortTitle: string; summary: string; description: string; sector: ProjectSector; applicationType: string; environment: ProjectEnvironment; city: string; district?: string;
  coverImage: string; desktopCoverImage?: string; mobileCoverImage?: string; coverImageAlt: string; galleryImages: readonly ProjectImage[]; beforeImage?: ProjectImage; installationImages: readonly ProjectImage[]; completedImages: readonly ProjectImage[]; detailImages: readonly ProjectImage[];
  videos: readonly ProjectVideo[]; clientName?: string; clientLogo?: string; clientLogoAlt?: string; products: readonly string[]; services: readonly string[]; technicalHighlights: readonly string[]; screenDimensions?: string; pixelPitch?: string; completionDate?: string;
  featured: boolean; status: ProjectStatus; isPlaceholder: boolean; publicationPermission: ProjectPermission; imagePermission: ProjectPermission; videoPermission: ProjectPermission; productHref?: string; href?: string;
};
const demo = (project: Omit<SectorProject, "status" | "isPlaceholder" | "publicationPermission" | "imagePermission" | "videoPermission" | "galleryImages" | "installationImages" | "completedImages" | "detailImages" | "videos" | "featured">): SectorProject => ({ ...project, status: "placeholder", isPlaceholder: true, publicationPermission: "denied", imagePermission: "granted", videoPermission: "denied", featured: false, galleryImages: [{ src: project.coverImage, alt: project.coverImageAlt, kind: "completed", order: 1 }], installationImages: [], completedImages: [], detailImages: [], videos: [{ title: "Örnek proje video alanı", type: "local", url: "", posterImage: project.coverImage, posterAlt: project.coverImageAlt, description: "Video, yayın izni alındıktan sonra kullanıcı etkileşimiyle yüklenir.", publicationPermission: "denied", order: 1 }] });
export const placeholderProjects: readonly SectorProject[] = [
  demo({ id: "demo-retail", slug: "ornek-magaza", title: "Örnek Mağaza LED Ekran Yerleşimi", shortTitle: "Mağaza vitrini", summary: "Vitrin görünürlüğü ve yakın izleme için örnek kart düzeni.", description: "Bu kayıt gerçek müşteri veya proje değildir; yalnız arayüz değerlendirmesinde kullanılır.", sector: "Mağaza", applicationType: "Vitrin ekranı", environment: "İç mekân", city: "Örnek şehir", coverImage: "/images/visual-v3/retail-led.webp", coverImageAlt: "Mağaza alanında örnek LED ekran yerleşimi", products: ["İç mekân LED ekran"], services: ["Keşif ve projelendirme"], technicalHighlights: ["Yakın izleme", "Mimari yerleşim"] }),
  demo({ id: "demo-mall", slug: "ornek-avm", title: "Örnek AVM Ortak Alan Yerleşimi", shortTitle: "AVM ortak alanı", summary: "Geniş dolaşım alanı için örnek uygulama kartı.", description: "Bu kayıt gerçek müşteri veya proje değildir.", sector: "AVM", applicationType: "Mimari ekran yüzeyi", environment: "İç mekân", city: "Örnek şehir", coverImage: "/images/visual-v5/mall-led-wall.webp", coverImageAlt: "AVM ortak alanında örnek LED ekran yüzeyi", products: ["İç mekân LED ekran"], services: ["Sistem entegrasyonu"], technicalHighlights: ["Geniş görüş açısı"] }),
  demo({ id: "demo-stage", slug: "ornek-sahne", title: "Örnek Sahne LED Ekran Yerleşimi", shortTitle: "Sahne ekranı", summary: "Sahne görüş aksına uygun örnek kart düzeni.", description: "Bu kayıt gerçek organizasyon veya proje değildir.", sector: "Sahne ve organizasyon", applicationType: "Sahne görüntü yüzeyi", environment: "İç mekân", city: "Örnek şehir", coverImage: "/images/visual-v7/stage-led.webp", coverImageAlt: "Sahnede örnek LED ekran yerleşimi", products: ["İç mekân LED ekran"], services: ["Montaj ve devreye alma"], technicalHighlights: ["Görüntü kaynağı yönetimi"] }),
  demo({ id: "demo-arena", slug: "ornek-arena", title: "Örnek Arena LED Ekran Yerleşimi", shortTitle: "Arena ekranı", summary: "Tribün görüşüne göre düzenlenmiş örnek proje kartı.", description: "Bu kayıt gerçek spor tesisi veya proje değildir.", sector: "Spor salonu ve arena", applicationType: "Merkez ekran", environment: "İç mekân", city: "Örnek şehir", coverImage: "/images/visual-v7/arena-led.webp", coverImageAlt: "Spor arenasında örnek LED ekran yerleşimi", products: ["LED ekran sistemleri"], services: ["Kontrol sistemi entegrasyonu"], technicalHighlights: ["Uzak izleme"] }),
  demo({ id: "demo-facade", slug: "ornek-cephe", title: "Örnek Bina Cephesi Yerleşimi", shortTitle: "Cephe ekranı", summary: "Mimari yüzeye uyarlanan örnek dış mekân kartı.", description: "Bu kayıt gerçek bina veya proje değildir.", sector: "Bina cephesi", applicationType: "Cephe ekranı", environment: "Dış mekân", city: "Örnek şehir", coverImage: "/images/visual-v3/facade-led.webp", coverImageAlt: "Bina cephesinde örnek dış mekân LED ekran", products: ["Dış mekân LED ekran"], services: ["Taşıyıcı sistem koordinasyonu"], technicalHighlights: ["Çevresel koşullar"] }),
] as const;
export const sectorProjects: readonly SectorProject[] = [];
export const placeholderReferences: readonly ProjectReference[] = placeholderProjects.slice(0, 4).map((project, order) => ({ id: `ref-${project.id}`, brandName: "Örnek logo alanı", logoAlt: "Gerçek müşteri logosu için örnek yerleşim alanı", projectSlug: project.slug, sector: project.sector, publicationPermission: "denied", status: "placeholder", order, isPlaceholder: true }));
export const projectReferences: readonly ProjectReference[] = [];
export function isPublishableProject(project: SectorProject) { return project.status === "published" && !project.isPlaceholder && project.publicationPermission === "granted" && project.imagePermission === "granted"; }
export function getPublishedProjects(sector?: string) { return sectorProjects.filter((project) => isPublishableProject(project) && (!sector || project.sector === sector)); }
export function getVerifiedSectorProjects(sector?: string) { return getPublishedProjects(sector); }
export function getProjectShowcaseData() { return process.env.NODE_ENV === "development" ? placeholderProjects : getPublishedProjects(); }
export function getReferenceShowcaseData() { return process.env.NODE_ENV === "development" ? placeholderReferences : projectReferences.filter((reference) => reference.status === "published" && !reference.isPlaceholder && reference.publicationPermission === "granted"); }
